-- ============================================================
-- STOCK REAL IMPORT (VPS READY)
-- Purpose:
-- 1) Create staging table + indexes
-- 2) Create apply function (validate + update stock + write stock_movements)
-- 3) Provide execution steps for each import batch
-- ============================================================

-- ============================================================
-- [A] ONE-TIME SETUP
-- Run this section once on Supabase VPS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.stock_import_staging (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code TEXT NOT NULL,
    part_number TEXT NOT NULL,
    nama_cabang TEXT NOT NULL,
    qty NUMERIC(18, 4) NOT NULL,
    source_row INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stock_import_staging_batch
    ON public.stock_import_staging(batch_code);

CREATE INDEX IF NOT EXISTS idx_stock_import_staging_part_cabang
    ON public.stock_import_staging(part_number, nama_cabang);

COMMENT ON TABLE public.stock_import_staging IS
'Temporary staging table for stock real import before applying to public.stock.';

CREATE OR REPLACE FUNCTION public.apply_stock_import_staging(
    p_batch_code TEXT,
    p_reference_id TEXT DEFAULT 'EXCEL_IMPORT',
    p_notes TEXT DEFAULT 'Stock real import from Excel'
)
RETURNS TABLE (
    updated_rows BIGINT,
    movement_rows BIGINT,
    duplicate_keys BIGINT,
    fractional_qty_rows BIGINT,
    unmatched_barang BIGINT,
    unmatched_cabang BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_updated_rows BIGINT := 0;
    v_movement_rows BIGINT := 0;
    v_duplicate_keys BIGINT := 0;
    v_fractional_qty_rows BIGINT := 0;
    v_unmatched_barang BIGINT := 0;
    v_unmatched_cabang BIGINT := 0;
BEGIN
    IF p_batch_code IS NULL OR BTRIM(p_batch_code) = '' THEN
        RAISE EXCEPTION 'p_batch_code is required';
    END IF;

    SELECT COUNT(*)
    INTO v_fractional_qty_rows
    FROM public.stock_import_staging s
    WHERE s.batch_code = p_batch_code
      AND s.qty <> TRUNC(s.qty);

    IF v_fractional_qty_rows > 0 THEN
        RAISE EXCEPTION 'Fractional qty found for batch %: % row(s). Qty must be integer.', p_batch_code, v_fractional_qty_rows;
    END IF;

    SELECT COUNT(*)
    INTO v_duplicate_keys
    FROM (
        SELECT UPPER(BTRIM(s.part_number)) AS part_key,
               UPPER(BTRIM(s.nama_cabang)) AS cabang_key
        FROM public.stock_import_staging s
        WHERE s.batch_code = p_batch_code
        GROUP BY 1, 2
        HAVING COUNT(*) > 1
    ) d;

    IF v_duplicate_keys > 0 THEN
        RAISE EXCEPTION 'Duplicate part_number + nama_cabang found for batch %: % key(s).', p_batch_code, v_duplicate_keys;
    END IF;

    CREATE TEMP TABLE tmp_stock_import_src ON COMMIT DROP AS
    SELECT
        UPPER(BTRIM(s.part_number)) AS part_key,
        UPPER(BTRIM(s.nama_cabang)) AS cabang_key,
        SUM(s.qty)::INTEGER AS qty
    FROM public.stock_import_staging s
    WHERE s.batch_code = p_batch_code
    GROUP BY 1, 2;

    SELECT COUNT(*)
    INTO v_unmatched_barang
    FROM tmp_stock_import_src src
    LEFT JOIN public.barang b
        ON UPPER(BTRIM(b.part_number)) = src.part_key
    WHERE b.id IS NULL;

    IF v_unmatched_barang > 0 THEN
        RAISE EXCEPTION 'Unmatched part_number found for batch %: % row(s).', p_batch_code, v_unmatched_barang;
    END IF;

    SELECT COUNT(*)
    INTO v_unmatched_cabang
    FROM tmp_stock_import_src src
    LEFT JOIN public.cabang c
        ON UPPER(BTRIM(c.nama_cabang)) = src.cabang_key
    WHERE c.id IS NULL;

    IF v_unmatched_cabang > 0 THEN
        RAISE EXCEPTION 'Unmatched nama_cabang found for batch %: % row(s).', p_batch_code, v_unmatched_cabang;
    END IF;

    CREATE TEMP TABLE tmp_stock_import_target ON COMMIT DROP AS
    SELECT
        st.id AS stock_id,
        st.part_id,
        st.cabang_id,
        st.qty AS old_qty,
        src.qty AS new_qty
    FROM tmp_stock_import_src src
    JOIN public.barang b
        ON UPPER(BTRIM(b.part_number)) = src.part_key
    JOIN public.cabang c
        ON UPPER(BTRIM(c.nama_cabang)) = src.cabang_key
    JOIN public.stock st
        ON st.part_id = b.id
       AND st.cabang_id = c.id
    WHERE st.qty IS DISTINCT FROM src.qty;

    INSERT INTO public.stock_movements (
        part_id,
        cabang_id,
        qty_change,
        type,
        reference_id,
        notes,
        created_at
    )
    SELECT
        t.part_id,
        t.cabang_id,
        t.new_qty - t.old_qty,
        'ADJUSTMENT',
        p_reference_id,
        p_notes,
        NOW()
    FROM tmp_stock_import_target t;

    GET DIAGNOSTICS v_movement_rows = ROW_COUNT;

    UPDATE public.stock st
    SET
        qty = t.new_qty,
        updated_at = NOW()
    FROM tmp_stock_import_target t
    WHERE st.id = t.stock_id;

    GET DIAGNOSTICS v_updated_rows = ROW_COUNT;

    RETURN QUERY
    SELECT
        v_updated_rows,
        v_movement_rows,
        v_duplicate_keys,
        v_fractional_qty_rows,
        v_unmatched_barang,
        v_unmatched_cabang;
END;
$$;

COMMENT ON FUNCTION public.apply_stock_import_staging(TEXT, TEXT, TEXT) IS
'Validate and apply stock import batch from stock_import_staging into stock with stock_movements logging.';

-- ============================================================
-- [B] PER-BATCH EXECUTION
-- Repeat this section for each new file import
-- ============================================================

-- Optional cleanup before loading one batch
-- TRUNCATE TABLE public.stock_import_staging;

-- Then import CSV into public.stock_import_staging with columns:
-- batch_code,part_number,nama_cabang,qty,source_row

-- Quick check loaded rows
-- SELECT batch_code, COUNT(*) AS rows_count
-- FROM public.stock_import_staging
-- GROUP BY batch_code
-- ORDER BY batch_code DESC;

-- Apply one batch (replace with your batch code)
-- SELECT *
-- FROM public.apply_stock_import_staging(
--   'BATCH-2026-05-12',
--   'EXCEL_IMPORT_2026_05_12',
--   'Stock real import dari file Excel'
-- );

-- Verification
-- SELECT
--   COUNT(*) FILTER (WHERE qty = 0) AS qty_zero,
--   COUNT(*) FILTER (WHERE qty > 0) AS qty_positive,
--   COUNT(*) AS total_rows
-- FROM public.stock;

-- SELECT b.part_number, c.nama_cabang, s.qty
-- FROM public.stock s
-- JOIN public.barang b ON b.id = s.part_id
-- JOIN public.cabang c ON c.id = s.cabang_id
-- ORDER BY s.updated_at DESC
-- LIMIT 100;

-- SELECT reference_id, type, COUNT(*) AS movement_rows, SUM(qty_change) AS total_change
-- FROM public.stock_movements
-- WHERE reference_id = 'EXCEL_IMPORT_2026_05_12'
-- GROUP BY reference_id, type;
