-- ============================================================
-- FITUR: REQUEST PENGATURAN STOK (min/max) DARI ALUR BUAT MR
-- ============================================================
-- Saat user mau menambah item di MR tapi PN belum punya kebijakan stok
-- (max_qty belum di-set) ATAU stok sudah mentok max, user bisa kirim
-- "Request Pengaturan Stok" lewat quick action. Moderator/PPIC/PJO melihat
-- daftar PN yang perlu di-set di halaman khusus, lalu mengaturnya di /stock.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.stock_setting_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    part_id     BIGINT REFERENCES public.barang(id) ON DELETE CASCADE NOT NULL,
    cabang_id   BIGINT REFERENCES public.cabang(id) NOT NULL,
    part_number TEXT,
    part_name   TEXT,

    requested_by UUID REFERENCES public.profiles(id) NOT NULL,

    -- no_policy     : max_qty belum dikonfigurasi (belum ada kebijakan)
    -- limit_reached : stok sudah mencapai batas maksimum
    reason TEXT NOT NULL CHECK (reason IN ('no_policy', 'limit_reached')),
    note   TEXT,

    -- snapshot kondisi saat request dibuat (untuk konteks moderator)
    current_qty INTEGER,
    max_qty     INTEGER,

    status TEXT NOT NULL DEFAULT 'open'
      CHECK (status IN ('open', 'resolved')),
    resolved_by UUID REFERENCES public.profiles(id),
    resolved_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.stock_setting_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to stock_setting_requests"
  ON public.stock_setting_requests;
CREATE POLICY "Allow authenticated full access to stock_setting_requests"
  ON public.stock_setting_requests FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_stock_setting_requests_cabang ON public.stock_setting_requests(cabang_id);
CREATE INDEX IF NOT EXISTS idx_stock_setting_requests_status ON public.stock_setting_requests(status);
CREATE INDEX IF NOT EXISTS idx_stock_setting_requests_part   ON public.stock_setting_requests(part_id);

-- Cegah duplikat: hanya boleh ada 1 request OPEN per (part, cabang).
CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_setting_requests_open
  ON public.stock_setting_requests(part_id, cabang_id)
  WHERE status = 'open';

DROP TRIGGER IF EXISTS update_stock_setting_requests_modtime ON public.stock_setting_requests;
CREATE TRIGGER update_stock_setting_requests_modtime BEFORE UPDATE ON public.stock_setting_requests
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
