-- Migration: Master site per customer (customer_sites)
-- Date: 2026-10-02
-- Description:
--   Consignment: saat customer dipilih, dropdown lokasi hanya menampilkan
--   site milik customer tersebut.
--     - SO Consignment: field "Site" yang tadinya teks bebas jadi dropdown
--       dari customer_sites milik customer terpilih.
--     - IK (Invoice Konsinyasi): dropdown "Gudang Tujuan" difilter ke cabang
--       yang terhubung ke site-site customer SO (customer_sites.cabang_id).
--
--   Backward-compat (deploy tidak atomik): kolom teks consignment_so.site
--   TETAP ada dan tetap diisi (nama site) -- v_consignment_dashboard & code
--   production lama masih membacanya. consignment_so.site_id baru, nullable.
--
--   Idempotent: aman di-run ulang.

-- 1. Tabel master site
CREATE TABLE IF NOT EXISTS public.customer_sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    site_name TEXT NOT NULL,
    alamat TEXT,
    -- Gudang (cabang) tempat stok konsinyasi site ini dikirim via IK. Opsional.
    cabang_id BIGINT REFERENCES public.cabang(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_sites_customer_name
  ON public.customer_sites(customer_id, UPPER(site_name));
CREATE INDEX IF NOT EXISTS idx_customer_sites_customer_id
  ON public.customer_sites(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_sites_cabang_id
  ON public.customer_sites(cabang_id);

ALTER TABLE public.customer_sites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to customer_sites"
  ON public.customer_sites;
CREATE POLICY "Allow authenticated full access to customer_sites"
  ON public.customer_sites FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.customer_sites TO anon, authenticated, authenticator;

DROP TRIGGER IF EXISTS update_customer_sites_modtime ON public.customer_sites;
CREATE TRIGGER update_customer_sites_modtime BEFORE UPDATE ON public.customer_sites
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 2. Relasi SO Consignment -> site
ALTER TABLE public.consignment_so
  ADD COLUMN IF NOT EXISTS site_id BIGINT REFERENCES public.customer_sites(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_consignment_so_site_id ON public.consignment_so(site_id);

-- 3. Backfill: site teks bebas yang sudah pernah dipakai di SO jadi master
--    site customer-nya, lalu SO lama dihubungkan ke site tersebut.
INSERT INTO public.customer_sites (customer_id, site_name)
SELECT DISTINCT ON (so.customer_id, UPPER(TRIM(so.site)))
       so.customer_id, UPPER(TRIM(so.site))
FROM public.consignment_so so
WHERE so.site IS NOT NULL AND TRIM(so.site) <> ''
ON CONFLICT (customer_id, UPPER(site_name)) DO NOTHING;

UPDATE public.consignment_so so
SET site_id = cs.id
FROM public.customer_sites cs
WHERE so.site_id IS NULL
  AND so.site IS NOT NULL
  AND cs.customer_id = so.customer_id
  AND UPPER(cs.site_name) = UPPER(TRIM(so.site));
