-- Migration: DO Reguler (Delivery Order tanpa SPB)
-- Date: 2026-06-02
-- Description:
--   Fitur DO Reguler: stock out ke CUSTOMER (eksternal) tanpa SPB & tanpa
--   approval berjenjang. Mirip Item Transfer namun:
--     - Tujuan = customer (bukan gudang), diambil dari tabel customers.
--     - Tambahan kolom kode_po sebagai informasi PO.
--     - TANPA approval/signature.
--   Pergerakan stok (standar DO / penjualan keluar):
--     - Stok KELUAR dari gudang pengirim saat DO Reguler dibuat (langsung).
--     - Status "Barang Diterima" hanya update status, TIDAK menambah stok di
--       mana pun (customer eksternal, tidak punya lokasi stok).
--     - Batalkan DO (hanya moderator): stok DIKEMBALIKAN ke gudang pengirim.
--   Tabel terpisah dari deliveries & item_transfers.

-- 1. Header
CREATE TABLE IF NOT EXISTS public.do_reguler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    do_kode TEXT UNIQUE NOT NULL,
    do_tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    dari_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) NOT NULL,

    -- Informasi tambahan
    kode_po TEXT,

    -- Detail pengiriman (mengikuti Item Transfer / deliveries)
    shipment_type TEXT NOT NULL DEFAULT 'ekspedisi',
      -- 'handcarry_internal' | 'handcarry_eksternal' | 'ekspedisi'
    ekspedisi TEXT,
    sender_name TEXT,
    eksternal_provider TEXT,
    eksternal_id TEXT,
    jumlah_koli INTEGER NOT NULL DEFAULT 1,
    no_resi TEXT,
    estimasi_hari INTEGER NOT NULL DEFAULT 1 CHECK (estimasi_hari >= 1),
    pic TEXT,
    remarks TEXT,

    -- Orang terkait (UUID auth.users; tanpa FK lintas-skema agar aman)
    uid_requester UUID,
    created_by UUID,

    -- Status & tracking (TANPA approval)
    status TEXT NOT NULL DEFAULT 'active',
      -- 'active' -> 'completed' (barang diterima) | 'cancelled'
    tracking_status TEXT NOT NULL DEFAULT 'created',
      -- 'created' | 'packing' | 'ready_pickup' | 'in_transit' | 'delivered'
    tracking_note TEXT,
    tracking_note_updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    tracking_note_updated_at TIMESTAMPTZ,

    -- Stok keluar dari gudang pengirim (TRUE saat dibuat; FALSE lagi bila dibatalkan)
    stock_released BOOLEAN NOT NULL DEFAULT FALSE,

    -- Pembatalan (hanya moderator)
    cancel_reason TEXT,
    cancelled_by UUID,
    cancelled_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT do_reguler_status_check
      CHECK (status IN ('active', 'completed', 'cancelled'))
);

-- 2. Item lines
CREATE TABLE IF NOT EXISTS public.do_reguler_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    do_id BIGINT REFERENCES public.do_reguler(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL CHECK (qty > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. RLS (tabel baru perlu policy eksplisit)
ALTER TABLE public.do_reguler ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.do_reguler_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to do_reguler"
  ON public.do_reguler FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated full access to do_reguler_items"
  ON public.do_reguler_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- 4. Index
CREATE INDEX IF NOT EXISTS idx_do_reguler_dari_cabang ON public.do_reguler(dari_cabang_id);
CREATE INDEX IF NOT EXISTS idx_do_reguler_customer ON public.do_reguler(customer_id);
CREATE INDEX IF NOT EXISTS idx_do_reguler_status ON public.do_reguler(status);
CREATE INDEX IF NOT EXISTS idx_do_reguler_items_do_id ON public.do_reguler_items(do_id);

-- 5. Trigger updated_at (mengikuti pola tabel lain)
CREATE TRIGGER update_do_reguler_modtime BEFORE UPDATE ON public.do_reguler
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_do_reguler_items_modtime BEFORE UPDATE ON public.do_reguler_items
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
