-- Staging table + helper function to import edited stock MIN/MAX from Excel/CSV.
-- Mirrors stock_real_import_staging (20260512093000) but targets min_qty/max_qty.
-- Update-only: does NOT create new stock rows, does NOT touch qty, no stock_movements.

CREATE TABLE IF NOT EXISTS public.stock_minmax_import_staging (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code TEXT NOT NULL,
    part_number TEXT NOT NULL,
    nama_cabang TEXT NOT NULL,
    min_qty NUMERIC(18, 4) NOT NULL DEFAULT 0,
    max_qty NUMERIC(18, 4) NOT NULL DEFAULT 0,
    source_row INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stock_minmax_staging_batch
    ON public.stock_minmax_import_staging(batch_code);

CREATE INDEX IF NOT EXISTS idx_stock_minmax_staging_part_cabang
    ON public.stock_minmax_import_staging(part_number, nama_cabang);

COMMENT ON TABLE public.stock_minmax_import_staging IS
'Staging table for editing stock min_qty/max_qty before applying to public.stock.';

CREATE OR REPLACE FUNCTION public.apply_stock_minmax_import_staging(
    p_batch_code TEXT
)
RETURNS TABLE (
    updated_rows BIGINT,
    duplicate_keys BIGINT,
    unmatched_barang BIGINT,
    unmatched_cabang BIGINT,
    negative_rows BIGINT,
    min_gt_max_rows BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_updated_rows BIGINT := 0;
    v_duplicate_keys BIGINT := 0;
    v_unmatched_barang BIGINT := 0;
    v_unmatched_cabang BIGINT := 0;
    v_negative_rows BIGINT := 0;
    v_min_gt_max_rows BIGINT := 0;
BEGIN
    IF p_batch_code IS NULL OR BTRIM(p_batch_code) = '' THEN
        RAISE EXCEPTION 'p_batch_code is required';
    END IF;

    -- 1. Negative values are not allowed.
    SELECT COUNT(*)
    INTO v_negative_rows
    FROM public.stock_minmax_import_staging s
    WHERE s.batch_code = p_batch_code
      AND (s.min_qty < 0 OR s.max_qty < 0);

    IF v_negative_rows > 0 THEN
        RAISE EXCEPTION 'Negative min/max found for batch %: % row(s).', p_batch_code, v_negative_rows;
    END IF;

    -- 2. Duplicate part+cabang keys.
    SELECT COUNT(*)
    INTO v_duplicate_keys
    FROM (
        SELECT UPPER(BTRIM(s.part_number)) AS part_key,
               UPPER(BTRIM(s.nama_cabang)) AS cabang_key
        FROM public.stock_minmax_import_staging s
        WHERE s.batch_code = p_batch_code
        GROUP BY 1, 2
        HAVING COUNT(*) > 1
    ) d;

    IF v_duplicate_keys > 0 THEN
        RAISE EXCEPTION 'Duplicate part_number + nama_cabang for batch %: % key(s).', p_batch_code, v_duplicate_keys;
    END IF;

    CREATE TEMP TABLE tmp_minmax_src ON COMMIT DROP AS
    SELECT
        UPPER(BTRIM(s.part_number)) AS part_key,
        UPPER(BTRIM(s.nama_cabang)) AS cabang_key,
        MAX(s.min_qty)::INTEGER AS min_qty,
        MAX(s.max_qty)::INTEGER AS max_qty
    FROM public.stock_minmax_import_staging s
    WHERE s.batch_code = p_batch_code
    GROUP BY 1, 2;

    -- 3. Unmatched part_number.
    SELECT COUNT(*)
    INTO v_unmatched_barang
    FROM tmp_minmax_src src
    LEFT JOIN public.barang b ON UPPER(BTRIM(b.part_number)) = src.part_key
    WHERE b.id IS NULL;

    IF v_unmatched_barang > 0 THEN
        RAISE EXCEPTION 'Unmatched part_number for batch %: % row(s).', p_batch_code, v_unmatched_barang;
    END IF;

    -- 4. Unmatched cabang.
    SELECT COUNT(*)
    INTO v_unmatched_cabang
    FROM tmp_minmax_src src
    LEFT JOIN public.cabang c ON UPPER(BTRIM(c.nama_cabang)) = src.cabang_key
    WHERE c.id IS NULL;

    IF v_unmatched_cabang > 0 THEN
        RAISE EXCEPTION 'Unmatched nama_cabang for batch %: % row(s).', p_batch_code, v_unmatched_cabang;
    END IF;

    -- Informational only (not blocking): min > max.
    SELECT COUNT(*) INTO v_min_gt_max_rows
    FROM tmp_minmax_src src
    WHERE src.min_qty > src.max_qty;

    CREATE TEMP TABLE tmp_minmax_target ON COMMIT DROP AS
    SELECT
        st.id AS stock_id,
        src.min_qty AS new_min,
        src.max_qty AS new_max
    FROM tmp_minmax_src src
    JOIN public.barang b ON UPPER(BTRIM(b.part_number)) = src.part_key
    JOIN public.cabang c ON UPPER(BTRIM(c.nama_cabang)) = src.cabang_key
    JOIN public.stock st ON st.part_id = b.id AND st.cabang_id = c.id
    WHERE st.min_qty IS DISTINCT FROM src.min_qty
       OR st.max_qty IS DISTINCT FROM src.max_qty;

    UPDATE public.stock st
    SET min_qty = t.new_min,
        max_qty = t.new_max,
        updated_at = NOW()
    FROM tmp_minmax_target t
    WHERE st.id = t.stock_id;

    GET DIAGNOSTICS v_updated_rows = ROW_COUNT;

    RETURN QUERY
    SELECT
        v_updated_rows,
        v_duplicate_keys,
        v_unmatched_barang,
        v_unmatched_cabang,
        v_negative_rows,
        v_min_gt_max_rows;
END;
$$;

COMMENT ON FUNCTION public.apply_stock_minmax_import_staging(TEXT) IS
'Validate and apply edited min_qty/max_qty from stock_minmax_import_staging into public.stock (update-only).';
