-- INVENTORY / STOCK (Maps to tb_stock)
CREATE TABLE public.stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT REFERENCES public.barang(id) ON DELETE CASCADE NOT NULL,
    qty INTEGER NOT NULL DEFAULT 0,
    min_qty INTEGER NOT NULL DEFAULT 0,
    max_qty INTEGER NOT NULL DEFAULT 0,
    cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Ensure unique stock location per part
    UNIQUE(part_id, cabang_id)
);

-- DELIVERIES (Maps to tb_delivery)
CREATE TABLE public.deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dlv_kode TEXT UNIQUE NOT NULL,
    mr_id BIGINT REFERENCES public.mrs(id), -- Nullable if not tied to MR
    dari_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    ke_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    ekspedisi TEXT NOT NULL,
    jumlah_koli INTEGER NOT NULL DEFAULT 0,
    pic TEXT NOT NULL,
    no_resi TEXT,
    status doc_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- DELIVERY ITEMS (Maps to dtl_delivery)
CREATE TABLE public.delivery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dlv_id BIGINT REFERENCES public.deliveries(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty_on_delivery INTEGER NOT NULL DEFAULT 0,
    qty_delivered INTEGER NOT NULL DEFAULT 0,
    qty_pending INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- JOB COSTING & SPB (Stubs based on typical WMS Finance patterns)
CREATE TABLE public.job_costing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_kode TEXT UNIQUE NOT NULL,
    cabang_id BIGINT REFERENCES public.cabang(id),
    description TEXT,
    total_cost NUMERIC DEFAULT 0,
    status doc_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.spb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_kode TEXT UNIQUE NOT NULL,
    po_id BIGINT REFERENCES public.pos(id),
    status doc_status NOT NULL DEFAULT 'open',
    total_amount NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Triggers
CREATE TRIGGER update_stock_modtime BEFORE UPDATE ON public.stock FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_deliveries_modtime BEFORE UPDATE ON public.deliveries FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_delivery_items_modtime BEFORE UPDATE ON public.delivery_items FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_job_costing_modtime BEFORE UPDATE ON public.job_costing FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_modtime BEFORE UPDATE ON public.spb FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
