-- Stock Out: Full SPB flow (SPB -> SPB PO -> SPB DO -> SPB Invoice -> Return SPB)

-- Replace stub table from initial inventory/finance schema.
DROP TABLE IF EXISTS public.spb CASCADE;

CREATE TABLE public.spb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_no TEXT UNIQUE NOT NULL,
    spb_tanggal TIMESTAMPTZ NOT NULL,
    spb_no_wo TEXT,
    spb_section TEXT,
    spb_pic_gmi TEXT,
    spb_pic_ppa TEXT,
    spb_kode_unit TEXT,
    spb_tipe_unit TEXT,
    spb_brand TEXT,
    spb_hm NUMERIC,
    spb_problem_remark TEXT,
    spb_status TEXT NOT NULL DEFAULT 'DONE QUOT',
    spb_gudang TEXT,
    cabang_id BIGINT REFERENCES public.cabang(id),
    spb_pic TEXT,
    spb_is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.spb_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_id BIGINT REFERENCES public.spb(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    dtl_spb_part_number TEXT NOT NULL,
    dtl_spb_part_name TEXT NOT NULL,
    dtl_spb_part_satuan TEXT NOT NULL,
    dtl_spb_qty INTEGER NOT NULL DEFAULT 0,
    dtl_spb_qty_returned INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.spb_po (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_id BIGINT REFERENCES public.spb(id) ON DELETE CASCADE NOT NULL,
    po_no TEXT NOT NULL,
    so_no TEXT,
    so_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(spb_id, po_no)
);

CREATE TABLE public.spb_po_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_po_id BIGINT REFERENCES public.spb_po(id) ON DELETE CASCADE NOT NULL,
    spb_dtl_id BIGINT REFERENCES public.spb_details(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(spb_po_id, spb_dtl_id)
);

CREATE TABLE public.spb_do (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_po_id BIGINT REFERENCES public.spb_po(id) ON DELETE CASCADE NOT NULL,
    do_no TEXT UNIQUE NOT NULL,
    do_date TIMESTAMPTZ,
    do_status_part TEXT DEFAULT 'DELIVERED',
    do_pic TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.spb_do_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_do_id BIGINT REFERENCES public.spb_do(id) ON DELETE CASCADE NOT NULL,
    spb_po_dtl_id BIGINT REFERENCES public.spb_po_details(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(spb_do_id, spb_po_dtl_id)
);

CREATE TABLE public.spb_invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_do_id BIGINT REFERENCES public.spb_do(id) ON DELETE CASCADE NOT NULL,
    invoice_no TEXT UNIQUE NOT NULL,
    invoice_date TIMESTAMPTZ,
    invoice_email_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.spb_invoice_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spb_invoice_id BIGINT REFERENCES public.spb_invoice(id) ON DELETE CASCADE NOT NULL,
    spb_do_dtl_id BIGINT REFERENCES public.spb_do_details(id) ON DELETE CASCADE NOT NULL,
    invoice_qty INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(spb_invoice_id, spb_do_dtl_id)
);

CREATE TABLE public.return_spb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rtn_kode TEXT UNIQUE NOT NULL,
    spb_id BIGINT REFERENCES public.spb(id) ON DELETE CASCADE NOT NULL,
    rtn_tanggal TIMESTAMPTZ NOT NULL,
    rtn_note TEXT,
    rtn_status TEXT NOT NULL DEFAULT 'Posted',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.return_spb_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rtn_id BIGINT REFERENCES public.return_spb(id) ON DELETE CASCADE NOT NULL,
    spb_dtl_id BIGINT REFERENCES public.spb_details(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    dtl_rtn_qty_return INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_spb_cabang_id ON public.spb(cabang_id);
CREATE INDEX idx_spb_status ON public.spb(spb_status);
CREATE INDEX idx_spb_details_spb_id ON public.spb_details(spb_id);
CREATE INDEX idx_spb_po_spb_id ON public.spb_po(spb_id);
CREATE INDEX idx_spb_po_details_spb_po_id ON public.spb_po_details(spb_po_id);
CREATE INDEX idx_spb_do_spb_po_id ON public.spb_do(spb_po_id);
CREATE INDEX idx_spb_do_details_spb_do_id ON public.spb_do_details(spb_do_id);
CREATE INDEX idx_spb_invoice_spb_do_id ON public.spb_invoice(spb_do_id);
CREATE INDEX idx_spb_invoice_details_invoice_id ON public.spb_invoice_details(spb_invoice_id);
CREATE INDEX idx_return_spb_spb_id ON public.return_spb(spb_id);
CREATE INDEX idx_return_spb_details_rtn_id ON public.return_spb_details(rtn_id);

CREATE OR REPLACE VIEW public.v_spb_report AS
SELECT
    s.id AS spb_id,
    s.spb_no,
    s.spb_tanggal,
    s.spb_no_wo,
    s.spb_section,
    s.spb_pic_gmi,
    s.spb_pic_ppa,
    s.spb_kode_unit,
    s.spb_tipe_unit,
    s.spb_brand,
    s.spb_hm,
    s.spb_problem_remark,
    s.spb_status,
    s.spb_gudang,
    s.created_at AS spb_created_at,
    sd.id AS spb_dtl_id,
    sd.dtl_spb_part_number,
    sd.dtl_spb_part_name,
    sd.dtl_spb_qty,
    sd.dtl_spb_part_satuan,
    po.po_no,
    po.so_no,
    po.so_date,
    po.created_at AS po_created_at,
    d.do_no,
    d.do_date,
    d.created_at AS do_created_at,
    i.invoice_no,
    i.invoice_date,
    i.invoice_email_date,
    i.created_at AS invoice_created_at
FROM public.spb s
JOIN public.spb_details sd ON sd.spb_id = s.id
LEFT JOIN public.spb_po_details pod ON pod.spb_dtl_id = sd.id
LEFT JOIN public.spb_po po ON po.id = pod.spb_po_id
LEFT JOIN public.spb_do_details dod ON dod.spb_po_dtl_id = pod.id
LEFT JOIN public.spb_do d ON d.id = dod.spb_do_id
LEFT JOIN public.spb_invoice_details idtl ON idtl.spb_do_dtl_id = dod.id
LEFT JOIN public.spb_invoice i ON i.id = idtl.spb_invoice_id
WHERE s.spb_is_deleted = FALSE;

CREATE TRIGGER update_spb_modtime BEFORE UPDATE ON public.spb FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_details_modtime BEFORE UPDATE ON public.spb_details FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_po_modtime BEFORE UPDATE ON public.spb_po FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_po_details_modtime BEFORE UPDATE ON public.spb_po_details FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_do_modtime BEFORE UPDATE ON public.spb_do FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_do_details_modtime BEFORE UPDATE ON public.spb_do_details FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_invoice_modtime BEFORE UPDATE ON public.spb_invoice FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_spb_invoice_details_modtime BEFORE UPDATE ON public.spb_invoice_details FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_return_spb_modtime BEFORE UPDATE ON public.return_spb FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_return_spb_details_modtime BEFORE UPDATE ON public.return_spb_details FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

ALTER TABLE public.spb ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_po ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_po_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_do ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_do_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spb_invoice_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_spb ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_spb_details ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS spb_authenticated_all ON public.spb;
DROP POLICY IF EXISTS spb_details_authenticated_all ON public.spb_details;
DROP POLICY IF EXISTS spb_po_authenticated_all ON public.spb_po;
DROP POLICY IF EXISTS spb_po_details_authenticated_all ON public.spb_po_details;
DROP POLICY IF EXISTS spb_do_authenticated_all ON public.spb_do;
DROP POLICY IF EXISTS spb_do_details_authenticated_all ON public.spb_do_details;
DROP POLICY IF EXISTS spb_invoice_authenticated_all ON public.spb_invoice;
DROP POLICY IF EXISTS spb_invoice_details_authenticated_all ON public.spb_invoice_details;
DROP POLICY IF EXISTS return_spb_authenticated_all ON public.return_spb;
DROP POLICY IF EXISTS return_spb_details_authenticated_all ON public.return_spb_details;

CREATE POLICY spb_authenticated_all ON public.spb FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_details_authenticated_all ON public.spb_details FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_po_authenticated_all ON public.spb_po FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_po_details_authenticated_all ON public.spb_po_details FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_do_authenticated_all ON public.spb_do FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_do_details_authenticated_all ON public.spb_do_details FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_invoice_authenticated_all ON public.spb_invoice FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY spb_invoice_details_authenticated_all ON public.spb_invoice_details FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY return_spb_authenticated_all ON public.return_spb FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY return_spb_details_authenticated_all ON public.return_spb_details FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
