-- Types
CREATE TYPE doc_status AS ENUM ('open', 'approved', 'rejected', 'done', 'closed');

-- MATERIAL REQUEST (Maps to tb_material_request)
CREATE TABLE public.mrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_kode TEXT UNIQUE NOT NULL,
    cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    mr_pic TEXT NOT NULL,
    mr_pic_id UUID REFERENCES public.profiles(id) NOT NULL,
    mr_tanggal DATE,
    mr_due_date DATE,
    mr_status doc_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.mr_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_id BIGINT REFERENCES public.mrs(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    prioritas TEXT,
    qty_request INTEGER NOT NULL DEFAULT 0,
    qty_received INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PURCHASE REQUEST (Maps to tb_purchase_request)
CREATE TABLE public.prs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_kode TEXT UNIQUE NOT NULL,
    cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    pr_pic_id UUID REFERENCES public.profiles(id) NOT NULL,
    pr_tanggal DATE NOT NULL,
    pr_status doc_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.pr_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id BIGINT REFERENCES public.prs(id) ON DELETE CASCADE NOT NULL,
    mr_id BIGINT REFERENCES public.mrs(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PURCHASE ORDER (Maps to tb_purchase_order)
CREATE TABLE public.pos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_kode TEXT UNIQUE NOT NULL,
    pr_id BIGINT REFERENCES public.prs(id) NOT NULL,
    vendor_id BIGINT REFERENCES public.vendors(id),
    po_tanggal DATE NOT NULL,
    po_estimasi DATE,
    po_keterangan TEXT,
    po_status doc_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.po_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id BIGINT REFERENCES public.pos(id) ON DELETE CASCADE NOT NULL,
    mr_id BIGINT REFERENCES public.mrs(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL DEFAULT 0,
    harga NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RECEIVE (Maps to tb_receive_item)
CREATE TABLE public.receives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ri_kode TEXT UNIQUE NOT NULL,
    po_id BIGINT REFERENCES public.pos(id) NOT NULL,
    cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    ri_pic TEXT NOT NULL,
    ri_tanggal DATE NOT NULL,
    ri_keterangan TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.receive_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ri_id BIGINT REFERENCES public.receives(id) ON DELETE CASCADE NOT NULL,
    po_id BIGINT REFERENCES public.pos(id) NOT NULL,
    mr_id BIGINT REFERENCES public.mrs(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Triggers
CREATE TRIGGER update_mrs_modtime BEFORE UPDATE ON public.mrs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_mr_items_modtime BEFORE UPDATE ON public.mr_items FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_prs_modtime BEFORE UPDATE ON public.prs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_pr_items_modtime BEFORE UPDATE ON public.pr_items FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_pos_modtime BEFORE UPDATE ON public.pos FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_po_items_modtime BEFORE UPDATE ON public.po_items FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_receives_modtime BEFORE UPDATE ON public.receives FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_receive_items_modtime BEFORE UPDATE ON public.receive_items FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
