-- Forecasting AC — isian jadwal bulanan ala "Forcasting AC.xlsx" (PA Forecast
-- & Monthly Planning PM Schedule): per unit per bulan ada SMU reading, jam
-- downtime terjadwal per tanggal (kolom 01–31), estimasi unscheduled, target
-- %PA, dan "Repair Option Required" (mis. "PMS 4000 & PMS 250").
-- Est. Total Down Time & %PA dihitung di app (lib/hm-ac.ts).
--
-- Objek baru saja, aman untuk build production lama. Idempotent. Butuh
-- 20261005120000_hm_ac_forecast.sql.

CREATE TABLE IF NOT EXISTS public.hm_ac_schedules (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id            BIGINT    NOT NULL REFERENCES public.hm_units(id) ON DELETE CASCADE,
  -- Bulan jadwal, selalu tanggal 1.
  period             DATE      NOT NULL CHECK (EXTRACT(DAY FROM period) = 1),
  -- Index 0 = tanggal 1. Panjang = jumlah hari di bulan tsb.
  day_hours          NUMERIC[] NOT NULL DEFAULT '{}' CHECK (COALESCE(array_length(day_hours, 1), 0) <= 31),
  smu_hm             INTEGER   CHECK (smu_hm >= 0),
  repair_option      TEXT      NOT NULL DEFAULT '',
  target_pa          NUMERIC   NOT NULL DEFAULT 92 CHECK (target_pa >= 0 AND target_pa <= 100),
  unscheduled_hours  NUMERIC   NOT NULL DEFAULT 0 CHECK (unscheduled_hours >= 0),
  note               TEXT      NOT NULL DEFAULT '',
  created_by         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (unit_id, period)
);
CREATE INDEX IF NOT EXISTS hm_ac_schedules_period_idx ON public.hm_ac_schedules(period);

DROP TRIGGER IF EXISTS update_hm_ac_schedules_modtime ON public.hm_ac_schedules;
CREATE TRIGGER update_hm_ac_schedules_modtime
  BEFORE UPDATE ON public.hm_ac_schedules
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

ALTER TABLE public.hm_ac_schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS hm_ac_schedules_read ON public.hm_ac_schedules;
CREATE POLICY hm_ac_schedules_read ON public.hm_ac_schedules FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_ac_schedules_write ON public.hm_ac_schedules;
CREATE POLICY hm_ac_schedules_write ON public.hm_ac_schedules FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_ac_schedules TO authenticated;
