-- ============================================================
-- FITUR: PLANNING SUPPLY + DEADLINE SHARE STOCK + FREEZE MR
-- ============================================================
-- Ringkasan:
--   1. Deadline per item pada alokasi share stock (diisi approver terakhir).
--   2. Tabel planning_supplies: saldo "barang akan masuk" per cabang tujuan,
--      dibuat saat delivery dibuat, ditutup saat barang diterima, di-void saat
--      delivery dibatalkan.
--   3. Kolom freeze pada mrs + tabel mr_freeze_reports (laporan kendala ke
--      moderator). MR ter-freeze jika ada alokasi yang lewat deadline DAN belum
--      ada delivery sama sekali untuk alokasi tsb (cek lazy di server actions).
--   4. Status 'cancelled' pada doc_status + kolom pembatalan di deliveries.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Deadline per item pada alokasi share stock
-- ------------------------------------------------------------
ALTER TABLE public.mr_sharestock_allocations
  ADD COLUMN IF NOT EXISTS deadline DATE;

-- ------------------------------------------------------------
-- 2. Status 'cancelled' untuk doc_status (idempotent, pola Chapter C6)
--    Dipakai oleh deliveries saat dibatalkan. TIDAK termasuk
--    DELIVERY_ACTIVE_STATUSES sehingga tidak memakan jatah alokasi.
-- ------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_enum
    WHERE enumlabel = 'cancelled'
      AND enumtypid = 'doc_status'::regtype
  ) THEN
    ALTER TYPE public.doc_status ADD VALUE 'cancelled';
  END IF;
END
$$;

-- ------------------------------------------------------------
-- 3. Kolom pembatalan pada deliveries (share stock)
-- ------------------------------------------------------------
ALTER TABLE public.deliveries
  ADD COLUMN IF NOT EXISTS cancel_reason TEXT,
  ADD COLUMN IF NOT EXISTS cancelled_by  UUID REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS cancelled_at  TIMESTAMPTZ;

-- ------------------------------------------------------------
-- 4. Kolom freeze pada mrs
-- ------------------------------------------------------------
ALTER TABLE public.mrs
  ADD COLUMN IF NOT EXISTS is_frozen     BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS frozen_at     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS frozen_reason TEXT;

CREATE INDEX IF NOT EXISTS idx_mrs_is_frozen ON public.mrs(is_frozen);

-- ------------------------------------------------------------
-- 5. Tabel planning_supplies
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.planning_supplies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mr_id            BIGINT REFERENCES public.mrs(id) ON DELETE CASCADE,
    mr_item_id       BIGINT REFERENCES public.mr_items(id) ON DELETE SET NULL,
    dlv_id           BIGINT REFERENCES public.deliveries(id) ON DELETE CASCADE NOT NULL,
    delivery_item_id BIGINT REFERENCES public.delivery_items(id) ON DELETE SET NULL,

    part_id     BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT,
    part_name   TEXT,
    satuan      TEXT,

    source_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    dest_cabang_id   BIGINT REFERENCES public.cabang(id) NOT NULL,

    qty      INTEGER NOT NULL CHECK (qty > 0),
    deadline DATE,

    -- in_transit : barang sudah keluar dari sumber, dalam pengiriman
    -- received   : barang diterima di tujuan (saldo planning supply ditutup)
    -- cancelled  : delivery dibatalkan, qty dikembalikan ke sumber
    status TEXT NOT NULL DEFAULT 'in_transit'
      CHECK (status IN ('in_transit', 'received', 'cancelled')),
    note   TEXT,

    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.planning_supplies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to planning_supplies"
  ON public.planning_supplies FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_planning_supplies_dest_cabang ON public.planning_supplies(dest_cabang_id);
CREATE INDEX IF NOT EXISTS idx_planning_supplies_mr          ON public.planning_supplies(mr_id);
CREATE INDEX IF NOT EXISTS idx_planning_supplies_dlv         ON public.planning_supplies(dlv_id);
CREATE INDEX IF NOT EXISTS idx_planning_supplies_status      ON public.planning_supplies(status);

CREATE TRIGGER update_planning_supplies_modtime BEFORE UPDATE ON public.planning_supplies
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ------------------------------------------------------------
-- 6. Tabel mr_freeze_reports (laporan kendala MR yang ter-freeze)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mr_freeze_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mr_id       BIGINT REFERENCES public.mrs(id) ON DELETE CASCADE NOT NULL,
    reporter_id UUID REFERENCES public.profiles(id) NOT NULL,
    kendala     TEXT NOT NULL,

    status TEXT NOT NULL DEFAULT 'open'
      CHECK (status IN ('open', 'resolved')),

    -- aksi penyelesaian moderator: unfreeze (lanjut) | reset (deadline baru)
    resolution_action TEXT
      CHECK (resolution_action IN ('unfreeze', 'reset')),
    resolution  TEXT,
    resolved_by UUID REFERENCES public.profiles(id),

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

ALTER TABLE public.mr_freeze_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to mr_freeze_reports"
  ON public.mr_freeze_reports FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_mr_freeze_reports_mr     ON public.mr_freeze_reports(mr_id);
CREATE INDEX IF NOT EXISTS idx_mr_freeze_reports_status ON public.mr_freeze_reports(status);
