-- Notifications system: persistent table + real-time pending approvals function
-- Covers: document approval requests, approval events (approved/rejected/completed)

-- ============================================================
-- notifications table
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  title       TEXT NOT NULL,
  message     TEXT,
  document_type TEXT,
  document_id BIGINT,
  document_url TEXT,
  is_read     BOOLEAN NOT NULL DEFAULT FALSE,
  read_at     TIMESTAMPTZ,
  metadata    JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- type values: 'approval_needed' | 'approved' | 'rejected' | 'document_completed' | 'general'

ALTER TABLE public.notifications
  DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE public.notifications
  ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('approval_needed', 'approved', 'rejected', 'document_completed', 'general'));

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
  ON public.notifications(user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user_is_read
  ON public.notifications(user_id, is_read);

CREATE INDEX IF NOT EXISTS idx_notifications_created_at
  ON public.notifications(created_at DESC);

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Users see only their own notifications
DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
CREATE POLICY "notifications_select_own"
  ON public.notifications
  FOR SELECT
  USING (user_id = auth.uid());

-- Users can mark their own notifications read (UPDATE is_read, read_at only)
DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;
CREATE POLICY "notifications_update_own"
  ON public.notifications
  FOR UPDATE
  USING (user_id = auth.uid());

-- Service role inserts notifications (server actions use admin client)
-- No INSERT policy for authenticated role — only service_role bypasses RLS

-- ============================================================
-- Function: get_pending_approvals_for_user
-- Returns documents that have a pending approval step assigned to user_uuid
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_pending_approvals_for_user(user_uuid UUID)
RETURNS TABLE (
  document_type   TEXT,
  document_id     BIGINT,
  document_number TEXT,
  document_url    TEXT,
  status_col      TEXT,
  created_at      TIMESTAMPTZ,
  step_level      TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  -- Material Request
  SELECT
    'Material Request'::TEXT,
    id::BIGINT,
    mr_kode::TEXT,
    ('/mr/' || id::TEXT)::TEXT,
    mr_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.mrs
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Purchase Request
  SELECT
    'Purchase Request'::TEXT,
    id::BIGINT,
    pr_kode::TEXT,
    ('/pr/' || id::TEXT)::TEXT,
    pr_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.prs
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Purchase Order
  SELECT
    'Purchase Order'::TEXT,
    id::BIGINT,
    po_kode::TEXT,
    ('/po/' || id::TEXT)::TEXT,
    po_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.pos
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Receive Item
  SELECT
    'Receive Item'::TEXT,
    id::BIGINT,
    ri_kode::TEXT,
    ('/receive?highlight=' || id::TEXT)::TEXT,
    ri_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.receives
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Stock Out - SPB
  SELECT
    'Stock Out - SPB'::TEXT,
    id::BIGINT,
    spb_no::TEXT,
    ('/spb?highlight=' || id::TEXT)::TEXT,
    approval_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.spb
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Stock Out - SPB PO
  SELECT
    'Stock Out - SPB PO'::TEXT,
    id::BIGINT,
    po_no::TEXT,
    ('/spb/po?highlight=' || id::TEXT)::TEXT,
    approval_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.spb_po
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Stock Out - SPB DO
  SELECT
    'Stock Out - SPB DO'::TEXT,
    id::BIGINT,
    do_no::TEXT,
    ('/spb/do?highlight=' || id::TEXT)::TEXT,
    approval_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.spb_do
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Stock Out - SPB Invoice
  SELECT
    'Stock Out - SPB Invoice'::TEXT,
    id::BIGINT,
    invoice_no::TEXT,
    ('/spb/invoice?highlight=' || id::TEXT)::TEXT,
    approval_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.spb_invoice
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  UNION ALL

  -- Return SPB
  SELECT
    'Return SPB'::TEXT,
    id::BIGINT,
    rtn_kode::TEXT,
    ('/return-spb?highlight=' || id::TEXT)::TEXT,
    approval_status::TEXT,
    created_at,
    (
      SELECT elem->>'level'
      FROM jsonb_array_elements(approvals) AS elem
      WHERE elem->>'userid' = user_uuid::TEXT
        AND elem->>'status' = 'pending'
      LIMIT 1
    )
  FROM public.return_spb
  WHERE approvals @> ('[{"userid":"' || user_uuid::TEXT || '","status":"pending"}]')::jsonb

  ORDER BY created_at DESC;
$$;

-- Grant execution to authenticated users (function uses SECURITY DEFINER)
GRANT EXECUTE ON FUNCTION public.get_pending_approvals_for_user(UUID) TO authenticated;

-- ============================================================
-- Function: get_unread_notifications_count
-- Lightweight count for sidebar badge
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_unread_notifications_count(user_uuid UUID)
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT COUNT(*)
  FROM public.notifications
  WHERE user_id = user_uuid
    AND is_read = FALSE;
$$;

GRANT EXECUTE ON FUNCTION public.get_unread_notifications_count(UUID) TO authenticated;
