-- Migration: Invoice Konsinyasi (IK) untuk Consignment
-- Date: 2026-09-14
-- Description:
--   IK = dokumen pengiriman fisik barang Consignment dari satu gudang ke
--   gudang lain (Gd Asal -> Gd Tujuan), dengan No AWB. BEDA dari SO
--   Consignment induknya (yang murni pencatatan, tanpa gerak stok & tanpa
--   approval): IK BENAR-BENAR memindahkan stok (potong stok Gd Asal, tambah
--   stok Gd Tujuan) begitu disimpan — satu langkah, TANPA approval,
--   mengikuti pola stock_movements yang sama dengan Delivery/Item Transfer
--   (type 'IK').
--
--   Satu item SO Consignment BISA dikirim lewat lebih dari satu IK
--   (pengiriman sebagian/partial) — makanya item IK adalah tabel terpisah
--   yang merujuk ke consignment_so_items (bukan kolom langsung di situ),
--   supaya histori tiap pengiriman tetap lengkap tersimpan dan Dashboard
--   Consignment bisa menjumlahkan qty terkirim per item.

-- 1. Header
CREATE TABLE IF NOT EXISTS public.consignment_ik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ik_kode TEXT UNIQUE NOT NULL,
    ik_tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    so_id BIGINT REFERENCES public.consignment_so(id) NOT NULL,
    dari_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    ke_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    no_awb TEXT,
    no_po TEXT,
    remarks TEXT,

    created_by UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT consignment_ik_diff_cabang CHECK (dari_cabang_id <> ke_cabang_id)
);

-- 2. Item lines (1 baris = 1 pengiriman utk 1 item SO; boleh berulang utk
--    item SO yang sama kalau dikirim bertahap/partial)
CREATE TABLE IF NOT EXISTS public.consignment_ik_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ik_id BIGINT REFERENCES public.consignment_ik(id) ON DELETE CASCADE NOT NULL,
    so_item_id BIGINT REFERENCES public.consignment_so_items(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    part_number_customer TEXT,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL CHECK (qty > 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. RLS (tabel baru perlu policy eksplisit)
ALTER TABLE public.consignment_ik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consignment_ik_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to consignment_ik" ON public.consignment_ik;
CREATE POLICY "Allow authenticated full access to consignment_ik"
  ON public.consignment_ik FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to consignment_ik_items" ON public.consignment_ik_items;
CREATE POLICY "Allow authenticated full access to consignment_ik_items"
  ON public.consignment_ik_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- GRANT eksplisit: tabel baru tidak otomatis dapat privilege dari
-- 20260407230007_grant_schema_usage_to_anon.sql (GRANT tidak retroaktif),
-- lihat 20260728120000_fix_missing_table_grants.sql untuk kasus serupa.
GRANT ALL ON TABLE public.consignment_ik, public.consignment_ik_items
  TO anon, authenticated, authenticator;

-- 4. Index
CREATE INDEX IF NOT EXISTS idx_consignment_ik_so_id ON public.consignment_ik(so_id);
CREATE INDEX IF NOT EXISTS idx_consignment_ik_dari_cabang ON public.consignment_ik(dari_cabang_id);
CREATE INDEX IF NOT EXISTS idx_consignment_ik_ke_cabang ON public.consignment_ik(ke_cabang_id);
CREATE INDEX IF NOT EXISTS idx_consignment_ik_items_ik_id ON public.consignment_ik_items(ik_id);
CREATE INDEX IF NOT EXISTS idx_consignment_ik_items_so_item_id ON public.consignment_ik_items(so_item_id);

-- 5. Trigger updated_at (mengikuti pola tabel lain)
DROP TRIGGER IF EXISTS update_consignment_ik_modtime ON public.consignment_ik;
CREATE TRIGGER update_consignment_ik_modtime BEFORE UPDATE ON public.consignment_ik
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 6. Dashboard Consignment: tambahkan agregat IK per item SO (kolom baru di
--    AKHIR select list saja — CREATE OR REPLACE VIEW tidak boleh menghapus/
--    menata ulang kolom lama, cuma boleh menambah di akhir).
CREATE OR REPLACE VIEW public.v_consignment_dashboard AS
SELECT
    so.id AS so_id,
    so.so_no,
    so.so_tanggal_input,
    so.tgl_po_email_marketing,
    so.tgl_po_customer,
    so.due_date,
    so.no_po,
    so.site,
    so.customer_id,
    c.customer_name,
    c.customer_no,
    item.id AS item_id,
    item.part_id,
    item.part_number,
    item.part_name,
    item.satuan,
    item.qty,
    item.part_number_customer,
    so.created_at,
    so.updated_at,
    ik_agg.total_qty_ik,
    ik_agg.no_ik_terakhir,
    ik_agg.tgl_ik_terakhir,
    ik_agg.no_awb_terakhir,
    ik_agg.gudang_terakhir,
    CASE
      WHEN ik_agg.total_qty_ik IS NULL OR ik_agg.total_qty_ik = 0 THEN NULL
      WHEN ik_agg.total_qty_ik >= item.qty THEN 'Full'
      ELSE 'Partial'
    END AS partial_full,
    CASE
      WHEN ik_agg.tgl_ik_terakhir IS NULL THEN NULL
      ELSE (ik_agg.tgl_ik_terakhir - so.so_tanggal_input)
    END AS durasi_kirim_ik_so
FROM public.consignment_so so
JOIN public.consignment_so_items item ON item.so_id = so.id
LEFT JOIN public.customers c ON c.id = so.customer_id
LEFT JOIN LATERAL (
    SELECT
        SUM(iki.qty) AS total_qty_ik,
        (ARRAY_AGG(ik.ik_kode ORDER BY ik.ik_tanggal DESC, ik.id DESC))[1] AS no_ik_terakhir,
        (ARRAY_AGG(ik.ik_tanggal ORDER BY ik.ik_tanggal DESC, ik.id DESC))[1] AS tgl_ik_terakhir,
        (ARRAY_AGG(ik.no_awb ORDER BY ik.ik_tanggal DESC, ik.id DESC))[1] AS no_awb_terakhir,
        (ARRAY_AGG(
          cabang_asal.nama_cabang || ' → ' || cabang_tujuan.nama_cabang
          ORDER BY ik.ik_tanggal DESC, ik.id DESC
        ))[1] AS gudang_terakhir
    FROM public.consignment_ik_items iki
    JOIN public.consignment_ik ik ON ik.id = iki.ik_id
    JOIN public.cabang cabang_asal ON cabang_asal.id = ik.dari_cabang_id
    JOIN public.cabang cabang_tujuan ON cabang_tujuan.id = ik.ke_cabang_id
    WHERE iki.so_item_id = item.id
) ik_agg ON true;
