-- ============================================================
-- STEP 1: Bersihkan dependencies hulu (Policies) lalu hapus role lama
-- ============================================================
DROP POLICY IF EXISTS "Allow admins to update all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Allow admins to delete profiles" ON public.profiles;

ALTER TABLE public.profiles DROP COLUMN IF EXISTS role;
DROP TYPE IF EXISTS public.user_role;

-- ============================================================
-- STEP 2: Buat tabel roles (master daftar role)
-- ============================================================
CREATE TABLE public.roles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT UNIQUE NOT NULL,
  label       TEXT NOT NULL,
  description TEXT,
  color       TEXT NOT NULL DEFAULT 'default',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- STEP 3: Buat tabel role_permissions (role → halaman)
-- ============================================================
CREATE TABLE public.role_permissions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id    BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  page_path  TEXT NOT NULL,
  cabang_id  BIGINT REFERENCES public.cabang(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (role_id, page_path, cabang_id)
);

-- ============================================================
-- STEP 4: Buat tabel user_roles (junction: user ↔ role)
-- ============================================================
CREATE TABLE public.user_roles (
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role_id     BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, role_id)
);

-- ============================================================
-- STEP 5: Buat VIEW v_user_permissions
-- ============================================================
CREATE OR REPLACE VIEW public.v_user_permissions AS
SELECT
  ur.user_id,
  p.cabang_id  AS user_cabang_id,
  rp.page_path,
  rp.cabang_id AS permission_cabang_id
FROM public.user_roles ur
JOIN public.profiles p ON ur.user_id = p.id
JOIN public.role_permissions rp ON ur.role_id = rp.role_id
WHERE
  rp.cabang_id IS NULL 
  OR rp.cabang_id = p.cabang_id;

-- ============================================================
-- STEP 5b: Update Trigger sync profile (Handle Multi-Role at Signup)
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    role_id_val BIGINT;
    role_name_val TEXT;
BEGIN
  -- Insert profile (Tanpa kolom role)
  INSERT INTO public.profiles (id, nama, email, nrp, cabang_id, is_active)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nama', ''),
    NEW.email,
    NEW.raw_user_meta_data->>'nrp',
    (NEW.raw_user_meta_data->>'cabang_id')::bigint,
    COALESCE((NEW.raw_user_meta_data->>'is_active')::boolean, FALSE)
  );

  -- Handle Initial Role Assignment dari metadata
  role_name_val := COALESCE(NEW.raw_user_meta_data->>'role', 'warehouse');
  
  -- Cari ID role-nya (mapping dari nama role lama ke ID role baru)
  SELECT id INTO role_id_val FROM public.roles WHERE name = role_name_val;
  
  -- Jika ketemu, masukkan ke user_roles
  IF role_id_val IS NOT NULL THEN
    INSERT INTO public.user_roles (user_id, role_id)
    VALUES (NEW.id, role_id_val);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Pastikan trigger terpasang ulang
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================================
-- STEP 6: RLS (Row Level Security)
-- ============================================================
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Helper function untuk cek moderator (Security Definer untuk hindari rekursi)
CREATE OR REPLACE FUNCTION public.is_moderator()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles ur
    JOIN public.roles r ON ur.role_id = r.id
    WHERE ur.user_id = auth.uid() AND r.name = 'moderator'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Policies for public.roles
CREATE POLICY "Anyone authenticated can read roles"
  ON public.roles FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Moderators can insert roles"
  ON public.roles FOR INSERT WITH CHECK (public.is_moderator());

CREATE POLICY "Moderators can update roles"
  ON public.roles FOR UPDATE USING (public.is_moderator());

CREATE POLICY "Moderators can delete roles"
  ON public.roles FOR DELETE USING (public.is_moderator());

-- Policies for public.role_permissions
CREATE POLICY "Anyone authenticated can read role_permissions"
  ON public.role_permissions FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Moderators can insert role_permissions"
  ON public.role_permissions FOR INSERT WITH CHECK (public.is_moderator());

CREATE POLICY "Moderators can update role_permissions"
  ON public.role_permissions FOR UPDATE USING (public.is_moderator());

CREATE POLICY "Moderators can delete role_permissions"
  ON public.role_permissions FOR DELETE USING (public.is_moderator());

-- Policies for public.user_roles
CREATE POLICY "Anyone authenticated can read user_roles"
  ON public.user_roles FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Moderators can insert user_roles"
  ON public.user_roles FOR INSERT WITH CHECK (public.is_moderator());

CREATE POLICY "Moderators can update user_roles"
  ON public.user_roles FOR UPDATE USING (public.is_moderator());

CREATE POLICY "Moderators can delete user_roles"
  ON public.user_roles FOR DELETE USING (public.is_moderator());

-- Policies for public.profiles
CREATE POLICY "Moderators can update all profiles"
  ON public.profiles FOR UPDATE USING (public.is_moderator());

-- ============================================================
-- STEP 7: Seed data — 13 initial roles
-- ============================================================
INSERT INTO public.roles (name, label, description, color) VALUES
  ('moderator',  'Moderator',  'Akses penuh ke semua fitur dan manajemen sistem (Superuser)', 'orange'),
  ('admin',      'Admin Site', 'Administrator tingkat cabang atau site', 'red'),
  ('spv',        'SPV',        'Supervisor, dapat approve transaksi tertentu', 'yellow'),
  ('gl',         'GL',         'General Ledger, akses ke finance & job costing', 'purple'),
  ('pjo',        'PJO',        'Penanggung Jawab Operasional', 'blue'),
  ('manager',    'Manager',    'Akses managerial dan approval tingkat tinggi', 'indigo'),
  ('service',    'Service',    'Teknisi/service, akses ke inventory & delivery', 'cyan'),
  ('manufaktur', 'Manufaktur', 'Akses ke modul produksi dan stock', 'teal'),
  ('ppic',       'PPIC',       'Production Planning, akses MR & stock', 'green'),
  ('logistik',   'Logistik',   'Akses inventory, receive, dan delivery', 'lime'),
  ('purchasing', 'Purchasing', 'Akses MR, PR, PO, dan vendor management', 'amber'),
  ('vendor',     'Vendor',     'External vendor, akses terbatas', 'gray'),
  ('customer',   'Customer',   'External customer, akses terbatas', 'slate');

-- ============================================================
-- STEP 8: Seed permissions untuk role 'moderator' (Full Access)
-- ============================================================
INSERT INTO public.role_permissions (role_id, page_path)
SELECT r.id, p.path FROM public.roles r
CROSS JOIN (VALUES
  ('/dashboard'), ('/stock'), ('/receive'), ('/deliveries'),
  ('/peminjaman'), ('/mr'), ('/pr'), ('/po'), ('/spb'),
  ('/return-spb'), ('/job-costing'), ('/barang'), ('/vendors'),
  ('/customers'), ('/users'), ('/role-management')
) AS p(path)
WHERE r.name = 'moderator';
