-- Expand job_costing header table
ALTER TABLE public.job_costing
  ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- Job costing line items
CREATE TABLE IF NOT EXISTS public.job_costing_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES public.job_costing(id) ON DELETE CASCADE NOT NULL,
    description TEXT NOT NULL,
    qty NUMERIC NOT NULL DEFAULT 1,
    unit TEXT NOT NULL DEFAULT 'pcs',
    unit_price NUMERIC NOT NULL DEFAULT 0,
    po_id BIGINT REFERENCES public.pos(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.job_costing_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to job_costing_items"
  ON public.job_costing_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_job_costing_items_job_id ON public.job_costing_items(job_id);
CREATE INDEX IF NOT EXISTS idx_job_costing_items_po_id ON public.job_costing_items(po_id);
