-- Migration: Transfer Item (TI)
-- Date: 2026-05-31
-- Description:
--   Fitur Transfer Item: pemindahan stok antar gudang TANPA keterkaitan MR/PR/SS.
--   Mirip Delivery namun memakai approval workflow (template type "Item Transfer")
--   + tanda tangan, serta pergerakan stok DUA TAHAP:
--     - Stok KELUAR dari gudang asal saat TI disetujui penuh (approved).
--     - Stok MASUK ke gudang tujuan saat admin gudang tujuan konfirmasi terima.
--   Tabel terpisah dari deliveries.

-- 1. Header
CREATE TABLE IF NOT EXISTS public.transfer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ti_kode TEXT UNIQUE NOT NULL,
    ti_tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    dari_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    ke_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,

    -- Detail pengiriman (mengikuti deliveries)
    shipment_type TEXT NOT NULL DEFAULT 'ekspedisi',
      -- 'handcarry_internal' | 'handcarry_eksternal' | 'ekspedisi'
    ekspedisi TEXT,
    sender_name TEXT,
    eksternal_provider TEXT,
    eksternal_id TEXT,
    jumlah_koli INTEGER NOT NULL DEFAULT 1,
    no_resi TEXT,
    estimasi_hari INTEGER NOT NULL DEFAULT 1 CHECK (estimasi_hari >= 1),
    pic TEXT,
    remarks TEXT,

    -- Orang terkait (UUID auth.users; tanpa FK lintas-skema agar aman)
    uid_requester UUID,
    uid_pic UUID,
    uid_receiver UUID,
    created_by UUID,

    -- Approval (mengikuti mrs.approvals JSONB)
    approvals JSONB NOT NULL DEFAULT '[]'::jsonb,
    rejection_reason TEXT,

    -- Tanda tangan
    signature_requester_id UUID,
    signature_receiver_id UUID,
    signed_by_requester_at TIMESTAMPTZ,
    signed_by_receiver_at TIMESTAMPTZ,

    -- Status & tracking
    status public.doc_status NOT NULL DEFAULT 'open',
      -- open -> approved -> completed | rejected
    tracking_status TEXT NOT NULL DEFAULT 'created',
      -- 'created' | 'packing' | 'ready_pickup' | 'in_transit' | 'delivered' | 'completed'
    stock_released BOOLEAN NOT NULL DEFAULT FALSE,
      -- TRUE jika stok sudah dikeluarkan dari gudang asal (saat approved)

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT transfer_items_diff_cabang CHECK (dari_cabang_id <> ke_cabang_id)
);

-- 2. Item lines
CREATE TABLE IF NOT EXISTS public.transfer_item_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ti_id BIGINT REFERENCES public.transfer_items(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL CHECK (qty > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. RLS (tabel baru perlu policy eksplisit)
ALTER TABLE public.transfer_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfer_item_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to transfer_items"
  ON public.transfer_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated full access to transfer_item_items"
  ON public.transfer_item_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- 4. Index
CREATE INDEX IF NOT EXISTS idx_transfer_items_dari_cabang ON public.transfer_items(dari_cabang_id);
CREATE INDEX IF NOT EXISTS idx_transfer_items_ke_cabang ON public.transfer_items(ke_cabang_id);
CREATE INDEX IF NOT EXISTS idx_transfer_items_status ON public.transfer_items(status);
CREATE INDEX IF NOT EXISTS idx_transfer_item_items_ti_id ON public.transfer_item_items(ti_id);
