-- Job costing finish parts: multi-row finish part support (mirrors
-- job_costing_items pattern), each row with its own destination cabang.
CREATE TABLE IF NOT EXISTS public.job_costing_finish_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES public.job_costing(id) ON DELETE CASCADE,
    part_id BIGINT REFERENCES public.barang(id) ON DELETE SET NULL,
    part_number TEXT,
    part_name TEXT,
    qty NUMERIC NOT NULL DEFAULT 1,
    cabang_id BIGINT REFERENCES public.cabang(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.job_costing_finish_parts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to job_costing_finish_parts"
  ON public.job_costing_finish_parts FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- Grant included directly in this migration (not deferred to a later fix
-- migration) -- see 20260728120000_fix_missing_table_grants.sql: tables
-- created after 20260407230007_grant_schema_usage_to_anon.sql don't
-- automatically get the base GRANT, and PostgREST rejects every query with
-- "permission denied" until it's added explicitly, even with correct RLS.
GRANT ALL ON TABLE public.job_costing_finish_parts TO anon, authenticated, authenticator;

CREATE INDEX IF NOT EXISTS idx_job_costing_finish_parts_job_id ON public.job_costing_finish_parts(job_id);
CREATE INDEX IF NOT EXISTS idx_job_costing_finish_parts_part_id ON public.job_costing_finish_parts(part_id);
CREATE INDEX IF NOT EXISTS idx_job_costing_finish_parts_cabang_id ON public.job_costing_finish_parts(cabang_id);

-- Idempotency guard: marks whether this job costing's stock effect (material
-- OUT + finish part IN) has already been applied. Used to gate stock
-- mutation on the approved/completed status bucket, and to prevent
-- double-apply/double-reverse when status is toggled back and forth.
ALTER TABLE public.job_costing
  ADD COLUMN IF NOT EXISTS stock_applied_at TIMESTAMPTZ NULL;

-- Legacy single-finish-part columns on job_costing (finish_part_id,
-- finish_part_cabang_id, qty_finish_part, finish_part) are intentionally
-- KEPT, not dropped -- old deployed app code may still write to them during
-- the Vercel/Supabase-VPS deploy window (see AGENTS.md backward-compat rule).
