-- Periodic Maintenance (modul "HM Maintenance") — jadwal penggantian part
-- alat berat berdasarkan HM (hour meter). Port dari aplikasi Caffeine
-- "Panel Kontrol — Periodic Maintenance", spesifikasi lengkap di hm.md.
--
-- Penyesuaian terhadap spec (hm.md §10) untuk WMS-GMI:
--   - Baca: semua user login (authenticated), bukan publik/anon.
--   - Tulis ("admin" modul): moderator ATAU role "service", lewat
--     hm_is_admin(). Tidak ada tabel hm_admins.
--   - Unit punya gudang (hm_units.cabang_id, opsional).
--   - Part bisa di-link ke master barang (hm_parts.barang_id, opsional).
--     Kolom manual stock_on_hand dari spec DIGANTI stok WMS: stok barang di
--     gudang unit, atau total semua gudang kalau unit belum punya gudang.
--   - Catat penggantian bisa memotong stok WMS (qty_used) di gudang unit,
--     atomic di RPC hm_record_replacement + tercatat di stock_movements
--     (type 'HM_REPLACEMENT').
--
-- Semua objek baru (prefix hm_), tidak mengubah tabel lama -> aman untuk
-- build production lama. Idempotent.

-- ============================================================
-- 1. Helper admin modul
-- ============================================================

CREATE OR REPLACE FUNCTION public.hm_is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles ur
    JOIN public.roles r ON ur.role_id = r.id
    WHERE ur.user_id = auth.uid() AND r.name IN ('moderator', 'service')
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION public.hm_is_admin() TO authenticated;

-- ============================================================
-- 2. Tabel
-- ============================================================

CREATE TABLE IF NOT EXISTS public.hm_units (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT    NOT NULL,
  name        TEXT    NOT NULL,
  model       TEXT    NOT NULL,
  current_hm  INTEGER NOT NULL DEFAULT 0 CHECK (current_hm >= 0),
  -- Gudang unit: sumber stok part & tempat stok dipotong saat penggantian.
  cabang_id   BIGINT REFERENCES public.cabang(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hm_parts (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id             BIGINT  NOT NULL REFERENCES public.hm_units(id) ON DELETE CASCADE,
  barang_id           BIGINT  REFERENCES public.barang(id) ON DELETE SET NULL,
  code                TEXT    NOT NULL,
  name                TEXT    NOT NULL,
  -- >= 0 (bukan > 0) supaya setara backend asli; "> 0" ditegakkan form.
  interval_hm         INTEGER NOT NULL CHECK (interval_hm >= 0),
  last_replacement_hm INTEGER NOT NULL CHECK (last_replacement_hm >= 0),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS hm_parts_unit_id_idx ON public.hm_parts(unit_id);
CREATE INDEX IF NOT EXISTS hm_parts_barang_id_idx ON public.hm_parts(barang_id);

CREATE TABLE IF NOT EXISTS public.hm_replacements (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id    BIGINT  NOT NULL REFERENCES public.hm_parts(id) ON DELETE CASCADE,
  unit_id    BIGINT  NOT NULL REFERENCES public.hm_units(id) ON DELETE CASCADE,
  hm         INTEGER NOT NULL CHECK (hm >= 0),
  date       TIMESTAMPTZ NOT NULL,
  note       TEXT    NOT NULL DEFAULT '',
  -- Qty barang yang dipotong dari stok WMS (0 = tidak memotong stok).
  qty_used   INTEGER NOT NULL DEFAULT 0 CHECK (qty_used >= 0),
  cabang_id  BIGINT REFERENCES public.cabang(id) ON DELETE SET NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS hm_replacements_part_hm_idx ON public.hm_replacements(part_id, hm);
CREATE INDEX IF NOT EXISTS hm_replacements_unit_id_idx ON public.hm_replacements(unit_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hm_service_kind') THEN
    CREATE TYPE public.hm_service_kind AS ENUM ('rutin', 'perbaikan', 'inspeksi');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.hm_services (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id    BIGINT  NOT NULL REFERENCES public.hm_units(id) ON DELETE CASCADE,
  kind       public.hm_service_kind NOT NULL,
  date       TIMESTAMPTZ NOT NULL,
  hm         INTEGER NOT NULL CHECK (hm >= 0),
  note       TEXT    NOT NULL DEFAULT '',
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS hm_services_unit_id_idx ON public.hm_services(unit_id);

DROP TRIGGER IF EXISTS update_hm_units_modtime ON public.hm_units;
CREATE TRIGGER update_hm_units_modtime
  BEFORE UPDATE ON public.hm_units
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_hm_parts_modtime ON public.hm_parts;
CREATE TRIGGER update_hm_parts_modtime
  BEFORE UPDATE ON public.hm_parts
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- unit_id part tidak boleh berubah (sesuai updatePart asli).
CREATE OR REPLACE FUNCTION public.hm_parts_lock_unit()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.unit_id <> OLD.unit_id THEN
    RAISE EXCEPTION 'unit_id part tidak dapat diubah';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS hm_parts_lock_unit ON public.hm_parts;
CREATE TRIGGER hm_parts_lock_unit
  BEFORE UPDATE ON public.hm_parts
  FOR EACH ROW EXECUTE FUNCTION public.hm_parts_lock_unit();

-- ============================================================
-- 3. View turunan (logika hm.md §3)
-- ============================================================
-- stock_on_hand: NULL kalau part belum di-link ke barang. Kalau unit punya
-- gudang -> stok di gudang itu (0 kalau belum ada baris stock), selain itu
-- total semua gudang.

CREATE OR REPLACE VIEW public.hm_part_views WITH (security_invoker = true) AS
SELECT
  p.id,
  p.unit_id,
  p.barang_id,
  p.code,
  p.name,
  p.interval_hm,
  p.last_replacement_hm,
  (p.last_replacement_hm + p.interval_hm)                             AS due_hm,
  (p.last_replacement_hm + p.interval_hm) - COALESCE(u.current_hm, 0) AS remaining_hm,
  CASE
    WHEN (p.last_replacement_hm + p.interval_hm) - COALESCE(u.current_hm, 0) <= 0  THEN 'lewat'
    WHEN (p.last_replacement_hm + p.interval_hm) - COALESCE(u.current_hm, 0) <= 50 THEN 'segera'
    ELSE 'aman'
  END                                                                 AS status,
  CASE
    WHEN (p.last_replacement_hm + p.interval_hm) - COALESCE(u.current_hm, 0) <= 0  THEN 0
    WHEN (p.last_replacement_hm + p.interval_hm) - COALESCE(u.current_hm, 0) <= 50 THEN 1
    ELSE 2
  END                                                                 AS status_rank,
  EXISTS (
    SELECT 1 FROM public.hm_replacements r
    WHERE r.part_id = p.id AND r.hm >= p.last_replacement_hm
  )                                                                   AS replaced_this_interval,
  CASE
    WHEN p.barang_id IS NULL THEN NULL
    WHEN u.cabang_id IS NOT NULL THEN COALESCE((
      SELECT s.qty FROM public.stock s
      WHERE s.part_id = p.barang_id AND s.cabang_id = u.cabang_id
    ), 0)
    ELSE COALESCE((
      SELECT SUM(s.qty)::INTEGER FROM public.stock s
      WHERE s.part_id = p.barang_id
    ), 0)
  END                                                                 AS stock_on_hand,
  u.code                                                              AS unit_code,
  u.name                                                              AS unit_name
FROM public.hm_parts p
LEFT JOIN public.hm_units u ON u.id = p.unit_id;

-- Jadwal:        order by status_rank, remaining_hm, id
-- Part per unit: where unit_id = $1 order by id

CREATE OR REPLACE VIEW public.hm_unit_summaries WITH (security_invoker = true) AS
SELECT
  u.id, u.code, u.name, u.model, u.current_hm, u.cabang_id,
  COUNT(v.id)                                                AS part_count,
  COUNT(v.id) FILTER (WHERE v.status = 'aman')               AS aman_count,
  COUNT(v.id) FILTER (WHERE v.status = 'segera')             AS segera_count,
  COUNT(v.id) FILTER (WHERE v.status = 'lewat')              AS lewat_count,
  COUNT(v.id) FILTER (WHERE NOT v.replaced_this_interval)    AS not_replaced_count
FROM public.hm_units u
LEFT JOIN public.hm_part_views v ON v.unit_id = u.id
GROUP BY u.id;
-- Urutan: order by id

CREATE OR REPLACE VIEW public.hm_history WITH (security_invoker = true) AS
SELECT
  'Penggantian Part'::TEXT AS kind,
  0                        AS kind_order,
  r.id,
  COALESCE(u.code, '')     AS unit_code,
  COALESCE(u.name, '')     AS unit_name,
  COALESCE(p.name, '')     AS part_name,
  ''::TEXT                 AS service_kind,
  r.date, r.hm, r.note
FROM public.hm_replacements r
LEFT JOIN public.hm_units u ON u.id = r.unit_id
LEFT JOIN public.hm_parts p ON p.id = r.part_id
UNION ALL
SELECT
  'Servis Umum', 1, s.id,
  COALESCE(u.code, ''), COALESCE(u.name, ''), '',
  s.kind::TEXT, s.date, s.hm, s.note
FROM public.hm_services s
LEFT JOIN public.hm_units u ON u.id = s.unit_id;
-- Urutan: order by date desc, kind_order, id

-- ============================================================
-- 4. RPC catat penggantian (hm.md §3.8, atomic + potong stok)
-- ============================================================
-- Mengembalikan NULL kalau part tidak ada. lastReplacementHm hanya maju
-- kalau p_hm > nilai sekarang (HM sama/lebih kecil tetap jadi riwayat).
-- p_qty_used > 0 memotong stok barang part di gudang unit; gagal (seluruh
-- transaksi batal) kalau part belum di-link barang, unit belum punya gudang,
-- atau stok tidak cukup.

CREATE OR REPLACE FUNCTION public.hm_record_replacement(
  p_part_id  BIGINT,
  p_hm       INTEGER,
  p_date     TIMESTAMPTZ,
  p_note     TEXT,
  p_qty_used INTEGER DEFAULT 0
)
RETURNS public.hm_replacements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_part   public.hm_parts;
  v_unit   public.hm_units;
  v_rep    public.hm_replacements;
  v_stock  public.stock;
  v_barang public.barang;
  v_qty    INTEGER := COALESCE(p_qty_used, 0);
BEGIN
  IF NOT public.hm_is_admin() THEN
    RAISE EXCEPTION 'Tidak diizinkan: hanya admin';
  END IF;
  IF p_hm IS NULL OR p_hm < 0 THEN
    RAISE EXCEPTION 'HM saat ganti harus berupa angka.';
  END IF;
  IF v_qty < 0 THEN
    RAISE EXCEPTION 'Qty dipakai tidak boleh negatif.';
  END IF;

  SELECT * INTO v_part FROM public.hm_parts WHERE id = p_part_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  SELECT * INTO v_unit FROM public.hm_units WHERE id = v_part.unit_id;

  IF v_qty > 0 THEN
    IF v_part.barang_id IS NULL THEN
      RAISE EXCEPTION 'Part belum di-link ke master barang, stok tidak bisa dipotong.';
    END IF;
    IF v_unit.cabang_id IS NULL THEN
      RAISE EXCEPTION 'Unit belum punya gudang, stok tidak bisa dipotong.';
    END IF;

    SELECT * INTO v_barang FROM public.barang WHERE id = v_part.barang_id;
    SELECT * INTO v_stock FROM public.stock
    WHERE part_id = v_part.barang_id AND cabang_id = v_unit.cabang_id
    FOR UPDATE;

    IF NOT FOUND OR v_stock.qty < v_qty THEN
      RAISE EXCEPTION 'Stok % di gudang unit tidak mencukupi (tersedia %, dibutuhkan %).',
        v_barang.part_number, COALESCE(v_stock.qty, 0), v_qty;
    END IF;
  END IF;

  INSERT INTO public.hm_replacements (
    part_id, unit_id, hm, date, note, qty_used, cabang_id, created_by
  ) VALUES (
    v_part.id, v_part.unit_id, p_hm, p_date, COALESCE(p_note, ''), v_qty,
    CASE WHEN v_qty > 0 THEN v_unit.cabang_id END, auth.uid()
  )
  RETURNING * INTO v_rep;

  IF p_hm > v_part.last_replacement_hm THEN
    UPDATE public.hm_parts SET last_replacement_hm = p_hm WHERE id = v_part.id;
  END IF;

  IF v_qty > 0 THEN
    UPDATE public.stock SET qty = qty - v_qty WHERE id = v_stock.id;
    INSERT INTO public.stock_movements (
      part_id, cabang_id, qty_change, type, reference_id, created_by, notes
    ) VALUES (
      v_part.barang_id, v_unit.cabang_id, -v_qty, 'HM_REPLACEMENT',
      'HM-REP-' || v_rep.id, auth.uid(),
      'Penggantian part ' || v_part.name || ' unit ' || COALESCE(v_unit.code, '') ||
        ' @ ' || p_hm || ' HM'
    );
  END IF;

  RETURN v_rep;
END;
$$;

GRANT EXECUTE ON FUNCTION public.hm_record_replacement(BIGINT, INTEGER, TIMESTAMPTZ, TEXT, INTEGER) TO authenticated;

-- ============================================================
-- 5. RLS
-- ============================================================

ALTER TABLE public.hm_units        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hm_parts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hm_replacements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hm_services     ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS hm_units_read ON public.hm_units;
CREATE POLICY hm_units_read ON public.hm_units FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_parts_read ON public.hm_parts;
CREATE POLICY hm_parts_read ON public.hm_parts FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_replacements_read ON public.hm_replacements;
CREATE POLICY hm_replacements_read ON public.hm_replacements FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_services_read ON public.hm_services;
CREATE POLICY hm_services_read ON public.hm_services FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS hm_units_write ON public.hm_units;
CREATE POLICY hm_units_write ON public.hm_units FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());
DROP POLICY IF EXISTS hm_parts_write ON public.hm_parts;
CREATE POLICY hm_parts_write ON public.hm_parts FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());
-- Insert replacement hanya lewat RPC (SECURITY DEFINER); policy tulis tetap
-- ada untuk delete (cascade) / koreksi oleh admin.
DROP POLICY IF EXISTS hm_replacements_write ON public.hm_replacements;
CREATE POLICY hm_replacements_write ON public.hm_replacements FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());
DROP POLICY IF EXISTS hm_services_write ON public.hm_services;
CREATE POLICY hm_services_write ON public.hm_services FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_units        TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_parts        TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_replacements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_services     TO authenticated;
GRANT SELECT ON public.hm_part_views, public.hm_unit_summaries, public.hm_history TO authenticated;
