-- Forecasting AC (modul "HM Maintenance") — perkiraan servis AC unit per
-- bulan beserta kebutuhan part & biaya. Digitalisasi file "Forcasting AC.xlsx"
-- (PA Forecast & Monthly PM Schedule), di mana unit masuk forecast AC hanya
-- saat PMS besar (2000/4000/6000/8000 HM) dan part-nya berupa paket dasar per
-- model + part mayor tambahan (compressor, magnet clutch, dst) per unit.
--
-- Model data:
--   - hm_ac_packages / hm_ac_package_items: paket part AC dasar (per model).
--   - hm_ac_units: pengaturan AC per unit HM (section, paket, interval servis
--     AC, HM servis AC terakhir, rata-rata HM per hari untuk proyeksi tanggal).
--   - hm_ac_extra_items: part mayor tambahan per unit per bulan forecast.
--   - RPC hm_record_ac_service: catat servis AC selesai (majukan HM servis
--     terakhir + riwayat di hm_services), atomic.
-- Proyeksi jatuh tempo/bulan dihitung di app (lib/hm-ac.ts).
--
-- Semua objek baru (prefix hm_ac_), tidak mengubah tabel lama -> aman untuk
-- build production lama. Idempotent. Butuh migration
-- 20261005100000_hm_periodic_maintenance.sql (hm_units, hm_is_admin).

-- ============================================================
-- 1. Tabel
-- ============================================================

CREATE TABLE IF NOT EXISTS public.hm_ac_packages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  note        TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hm_ac_package_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id  BIGINT  NOT NULL REFERENCES public.hm_ac_packages(id) ON DELETE CASCADE,
  barang_id   BIGINT  REFERENCES public.barang(id) ON DELETE SET NULL,
  name        TEXT    NOT NULL,
  qty         NUMERIC NOT NULL DEFAULT 1 CHECK (qty > 0),
  unit_price  NUMERIC NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS hm_ac_package_items_package_idx ON public.hm_ac_package_items(package_id);

CREATE TABLE IF NOT EXISTS public.hm_ac_units (
  unit_id          BIGINT  PRIMARY KEY REFERENCES public.hm_units(id) ON DELETE CASCADE,
  section          TEXT    NOT NULL DEFAULT 'track' CHECK (section IN ('track', 'wheel', 'support')),
  package_id       BIGINT  REFERENCES public.hm_ac_packages(id) ON DELETE SET NULL,
  interval_hm      INTEGER NOT NULL DEFAULT 2000 CHECK (interval_hm > 0),
  last_service_hm  INTEGER NOT NULL DEFAULT 0 CHECK (last_service_hm >= 0),
  daily_hm         NUMERIC NOT NULL DEFAULT 20 CHECK (daily_hm > 0 AND daily_hm <= 24),
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS hm_ac_units_package_idx ON public.hm_ac_units(package_id);

CREATE TABLE IF NOT EXISTS public.hm_ac_extra_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id     BIGINT  NOT NULL REFERENCES public.hm_units(id) ON DELETE CASCADE,
  -- Bulan forecast, selalu tanggal 1 (mis. 2026-11-01).
  period      DATE    NOT NULL CHECK (EXTRACT(DAY FROM period) = 1),
  barang_id   BIGINT  REFERENCES public.barang(id) ON DELETE SET NULL,
  name        TEXT    NOT NULL,
  qty         NUMERIC NOT NULL DEFAULT 1 CHECK (qty > 0),
  unit_price  NUMERIC NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
  note        TEXT    NOT NULL DEFAULT '',
  created_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS hm_ac_extra_items_period_idx ON public.hm_ac_extra_items(period, unit_id);

DROP TRIGGER IF EXISTS update_hm_ac_packages_modtime ON public.hm_ac_packages;
CREATE TRIGGER update_hm_ac_packages_modtime
  BEFORE UPDATE ON public.hm_ac_packages
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_hm_ac_units_modtime ON public.hm_ac_units;
CREATE TRIGGER update_hm_ac_units_modtime
  BEFORE UPDATE ON public.hm_ac_units
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ============================================================
-- 2. RPC catat servis AC selesai
-- ============================================================
-- last_service_hm hanya maju kalau p_hm lebih besar; riwayat tetap dicatat
-- di hm_services (kind 'rutin') supaya muncul di riwayat/CSV modul HM.

CREATE OR REPLACE FUNCTION public.hm_record_ac_service(
  p_unit_id BIGINT,
  p_hm      INTEGER,
  p_date    TIMESTAMPTZ,
  p_note    TEXT
)
RETURNS public.hm_ac_units
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ac public.hm_ac_units;
BEGIN
  IF NOT public.hm_is_admin() THEN
    RAISE EXCEPTION 'Tidak diizinkan: hanya admin';
  END IF;
  IF p_hm IS NULL OR p_hm < 0 THEN
    RAISE EXCEPTION 'HM servis harus berupa angka.';
  END IF;

  SELECT * INTO v_ac FROM public.hm_ac_units WHERE unit_id = p_unit_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unit belum diatur untuk Forecasting AC.';
  END IF;

  INSERT INTO public.hm_services (unit_id, kind, date, hm, note, created_by)
  VALUES (
    p_unit_id, 'rutin', p_date, p_hm,
    TRIM('Servis AC. ' || COALESCE(p_note, '')), auth.uid()
  );

  IF p_hm > v_ac.last_service_hm THEN
    UPDATE public.hm_ac_units SET last_service_hm = p_hm
    WHERE unit_id = p_unit_id
    RETURNING * INTO v_ac;
  END IF;

  RETURN v_ac;
END;
$$;

GRANT EXECUTE ON FUNCTION public.hm_record_ac_service(BIGINT, INTEGER, TIMESTAMPTZ, TEXT) TO authenticated;

-- ============================================================
-- 3. RLS (baca: semua user login, tulis: hm_is_admin)
-- ============================================================

ALTER TABLE public.hm_ac_packages      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hm_ac_package_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hm_ac_units         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hm_ac_extra_items   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS hm_ac_packages_read ON public.hm_ac_packages;
CREATE POLICY hm_ac_packages_read ON public.hm_ac_packages FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_ac_package_items_read ON public.hm_ac_package_items;
CREATE POLICY hm_ac_package_items_read ON public.hm_ac_package_items FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_ac_units_read ON public.hm_ac_units;
CREATE POLICY hm_ac_units_read ON public.hm_ac_units FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS hm_ac_extra_items_read ON public.hm_ac_extra_items;
CREATE POLICY hm_ac_extra_items_read ON public.hm_ac_extra_items FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS hm_ac_packages_write ON public.hm_ac_packages;
CREATE POLICY hm_ac_packages_write ON public.hm_ac_packages FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());
DROP POLICY IF EXISTS hm_ac_package_items_write ON public.hm_ac_package_items;
CREATE POLICY hm_ac_package_items_write ON public.hm_ac_package_items FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());
DROP POLICY IF EXISTS hm_ac_units_write ON public.hm_ac_units;
CREATE POLICY hm_ac_units_write ON public.hm_ac_units FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());
DROP POLICY IF EXISTS hm_ac_extra_items_write ON public.hm_ac_extra_items;
CREATE POLICY hm_ac_extra_items_write ON public.hm_ac_extra_items FOR ALL TO authenticated
  USING (public.hm_is_admin()) WITH CHECK (public.hm_is_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_ac_packages      TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_ac_package_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_ac_units         TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hm_ac_extra_items   TO authenticated;
