-- Migration: MR Fulfillment & Rejection Logic
-- Adds fields to track rejection reasons and stock sharing allocations.

-- 1. Add rejection reason to mrs
ALTER TABLE public.mrs 
ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

-- 2. Add fulfillment trackers to mr_items
ALTER TABLE public.mr_items 
ADD COLUMN IF NOT EXISTS qty_pr INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS qty_sharestock_total INTEGER DEFAULT 0;

-- 3. Create Share-Stock Allocations table
CREATE TABLE IF NOT EXISTS public.mr_sharestock_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_item_id BIGINT REFERENCES public.mr_items(id) ON DELETE CASCADE NOT NULL,
    source_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    qty INTEGER NOT NULL CHECK (qty > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.mr_sharestock_allocations ENABLE ROW LEVEL SECURITY;

-- Policies for mr_sharestock_allocations
CREATE POLICY "Allow authenticated full access to mr_sharestock_allocations" 
ON public.mr_sharestock_allocations 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sharestock_mr_item_id ON public.mr_sharestock_allocations(mr_item_id);
CREATE INDEX IF NOT EXISTS idx_sharestock_source_cabang ON public.mr_sharestock_allocations(source_cabang_id);
