-- Migration: Sales Order Consignment
-- Date: 2026-09-03
-- Description:
--   Fitur SO Consignment (tahap 1 dari modul Consignment): pencatatan Sales
--   Order konsinyasi dari sistem lama (Excel) ke WMS-GMI. Murni data
--   perencanaan/tracking awal, TIDAK ada pergerakan stok & TIDAK ada
--   approval berjenjang. No. SO diinput manual (mengikuti nomor dari
--   sistem lama/marketing). "Site" = lokasi project customer (teks bebas),
--   BUKAN cabang GMI.
--   Field lain (Dashboard Consignment yang menyusul progress supply,
--   pengiriman, PR/PO, rekonsiliasi) akan ditambahkan di migration terpisah
--   setelah fitur ini disetujui user.

-- 1. Header
CREATE TABLE IF NOT EXISTS public.consignment_so (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_no TEXT UNIQUE NOT NULL,
    so_tanggal_input DATE NOT NULL DEFAULT CURRENT_DATE,
    tgl_po_email_marketing DATE,
    tgl_po_customer DATE,
    due_date DATE,
    no_po TEXT,
    customer_id BIGINT REFERENCES public.customers(id) NOT NULL,
    site TEXT,

    created_by UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Item lines
CREATE TABLE IF NOT EXISTS public.consignment_so_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_id BIGINT REFERENCES public.consignment_so(id) ON DELETE CASCADE NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    part_number_customer TEXT,
    code_item_customer TEXT,
    qty NUMERIC NOT NULL CHECK (qty > 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. RLS (tabel baru perlu policy eksplisit)
ALTER TABLE public.consignment_so ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consignment_so_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access to consignment_so"
  ON public.consignment_so FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated full access to consignment_so_items"
  ON public.consignment_so_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- GRANT eksplisit: tabel baru tidak otomatis dapat privilege dari
-- 20260407230007_grant_schema_usage_to_anon.sql (GRANT tidak retroaktif),
-- lihat 20260728120000_fix_missing_table_grants.sql untuk kasus serupa.
GRANT ALL ON TABLE public.consignment_so, public.consignment_so_items
  TO anon, authenticated, authenticator;

-- 4. Index
CREATE INDEX IF NOT EXISTS idx_consignment_so_customer ON public.consignment_so(customer_id);
CREATE INDEX IF NOT EXISTS idx_consignment_so_items_so_id ON public.consignment_so_items(so_id);
CREATE INDEX IF NOT EXISTS idx_consignment_so_items_part_id ON public.consignment_so_items(part_id);

-- 5. Trigger updated_at (mengikuti pola tabel lain)
CREATE TRIGGER update_consignment_so_modtime BEFORE UPDATE ON public.consignment_so
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_consignment_so_items_modtime BEFORE UPDATE ON public.consignment_so_items
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
