-- PO Non-PR + Job Costing sebagai konversi satuan + "Hubungkan ke PR".
-- Date: 2026-10-06
--
-- Kasus: PPIC naik PR dalam satuan "Pack of 100m Roll" (PN-A), tapi
-- purchasing beli dalam satuan dasar (PN-B "1m Roll" x100). PN-nya beda,
-- jadi PO tidak bisa ditarik dari PR. Alur baru:
--   1. PO jenis 'non_pr': item dipilih bebas dari master barang, tanpa
--      pr_item_id/mr_id. PR cuma jadi teks referensi (pos.po_pr_referensi).
--   2. RI dari PO Non-PR: barang mendarat di gudang GMI-JAKARTA (dikunci di
--      app, lihat lib/po-non-pr.ts), tanpa distribusi ke MR.
--   3. Job Costing: bahan = item PO Non-PR (job_costing_items.po_item_id),
--      finish part = PN-A, boleh langsung "dikirim ke MR"
--      (job_costing_finish_parts.mr_item_id) -> ikut menambah
--      mr_items.qty_received (lihat lib/mr-fulfillment.ts).
--   4. Escape plan: item PO Non-PR boleh di-link manual ke item PR yang ada
--      di WMS (po_item_pr_links, banyak-ke-banyak, qty_pr diisi manual dalam
--      satuan PR) supaya status konversi PR ikut terhitung. Hapus link cuma
--      moderator.
--
-- Backward compat (AGENTS.md / deploy tidak atomik): semua perubahan di sini
-- cuma MELONGGARKAN constraint lama atau MENAMBAH kolom/tabel nullable --
-- code production lama yang selalu isi pr_id/mr_id tetap jalan apa adanya.

-- ============================================================
-- 1. pos: PO boleh tanpa PR
-- ============================================================
ALTER TABLE public.pos ALTER COLUMN pr_id DROP NOT NULL;

ALTER TABLE public.pos
  ADD COLUMN IF NOT EXISTS po_jenis TEXT NOT NULL DEFAULT 'reguler',
  ADD COLUMN IF NOT EXISTS po_pr_referensi TEXT,
  ADD COLUMN IF NOT EXISTS cabang_id BIGINT REFERENCES public.cabang(id) ON DELETE SET NULL;

ALTER TABLE public.pos DROP CONSTRAINT IF EXISTS pos_po_jenis_check;
ALTER TABLE public.pos ADD CONSTRAINT pos_po_jenis_check
  CHECK (po_jenis IN ('reguler', 'non_pr'));

-- PO reguler tetap wajib punya PR (perilaku lama tidak berubah).
ALTER TABLE public.pos DROP CONSTRAINT IF EXISTS pos_reguler_requires_pr_check;
ALTER TABLE public.pos ADD CONSTRAINT pos_reguler_requires_pr_check
  CHECK (po_jenis <> 'reguler' OR pr_id IS NOT NULL);

-- pos.cabang_id: lokasi PO sendiri. Dulu lokasi PO selalu diturunkan dari
-- prs.cabang_id; PO Non-PR tidak punya PR, jadi butuh kolom sendiri. Backfill
-- dari PR untuk PO lama, dan trigger mengisi otomatis untuk insert dari code
-- production lama (yang belum tahu kolom ini) supaya filter lokasi di list PO
-- (sekarang pakai pos.cabang_id) tetap lengkap.
UPDATE public.pos p
  SET cabang_id = pr.cabang_id
  FROM public.prs pr
  WHERE pr.id = p.pr_id AND p.cabang_id IS NULL;

CREATE OR REPLACE FUNCTION public.pos_fill_cabang_from_pr()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.cabang_id IS NULL AND NEW.pr_id IS NOT NULL THEN
    SELECT cabang_id INTO NEW.cabang_id FROM public.prs WHERE id = NEW.pr_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pos_fill_cabang_from_pr ON public.pos;
CREATE TRIGGER trg_pos_fill_cabang_from_pr
  BEFORE INSERT OR UPDATE OF pr_id ON public.pos
  FOR EACH ROW EXECUTE FUNCTION public.pos_fill_cabang_from_pr();

CREATE INDEX IF NOT EXISTS idx_pos_cabang_id ON public.pos(cabang_id);
CREATE INDEX IF NOT EXISTS idx_pos_po_jenis ON public.pos(po_jenis);

-- ============================================================
-- 2. po_items / receive_items: boleh tanpa MR
-- ============================================================
ALTER TABLE public.po_items ALTER COLUMN mr_id DROP NOT NULL;
ALTER TABLE public.receive_items ALTER COLUMN mr_id DROP NOT NULL;

-- ============================================================
-- 3. po_item_pr_links: "Hubungkan ke PR" (banyak-ke-banyak)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.po_item_pr_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_item_id BIGINT NOT NULL REFERENCES public.po_items(id) ON DELETE CASCADE,
    pr_item_id BIGINT NOT NULL REFERENCES public.pr_items(id) ON DELETE CASCADE,
    -- Qty dalam SATUAN PR (mis. 1 pack), diisi manual -- PN/satuan PO & PR
    -- beda, sistem tidak bisa mengkonversi sendiri.
    qty_pr NUMERIC NOT NULL CHECK (qty_pr > 0),
    notes TEXT,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (po_item_id, pr_item_id)
);

ALTER TABLE public.po_item_pr_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "po_item_pr_links_select" ON public.po_item_pr_links;
CREATE POLICY "po_item_pr_links_select"
  ON public.po_item_pr_links FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "po_item_pr_links_insert" ON public.po_item_pr_links;
CREATE POLICY "po_item_pr_links_insert"
  ON public.po_item_pr_links FOR INSERT TO authenticated
  WITH CHECK (true);

-- Hapus link cuma moderator (keputusan user 2026-10-06). Tidak ada policy
-- UPDATE: ubah qty = hapus lalu link ulang.
DROP POLICY IF EXISTS "po_item_pr_links_delete" ON public.po_item_pr_links;
CREATE POLICY "po_item_pr_links_delete"
  ON public.po_item_pr_links FOR DELETE TO authenticated
  USING (public.is_moderator());

GRANT ALL ON TABLE public.po_item_pr_links TO anon, authenticated, authenticator;

CREATE INDEX IF NOT EXISTS idx_po_item_pr_links_po_item_id ON public.po_item_pr_links(po_item_id);
CREATE INDEX IF NOT EXISTS idx_po_item_pr_links_pr_item_id ON public.po_item_pr_links(pr_item_id);

-- ============================================================
-- 4. Job Costing: lacak pemakaian per item PO + kirim finish part ke MR
-- ============================================================
ALTER TABLE public.job_costing_items
  ADD COLUMN IF NOT EXISTS po_item_id BIGINT REFERENCES public.po_items(id) ON DELETE SET NULL;

ALTER TABLE public.job_costing_finish_parts
  ADD COLUMN IF NOT EXISTS mr_item_id BIGINT REFERENCES public.mr_items(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_job_costing_items_po_item_id ON public.job_costing_items(po_item_id);
CREATE INDEX IF NOT EXISTS idx_job_costing_finish_parts_mr_item_id ON public.job_costing_finish_parts(mr_item_id);

COMMENT ON COLUMN public.pos.po_jenis IS
'reguler = item ditarik dari PR WMS (pr_item_id wajib). non_pr = item bebas dari master barang, PR hanya referensi teks (po_pr_referensi) + link opsional via po_item_pr_links.';
COMMENT ON COLUMN public.job_costing_finish_parts.mr_item_id IS
'Finish part ini dikirim untuk memenuhi item MR tsb. Dihitung ke mr_items.qty_received selama job costing stock_applied_at IS NOT NULL (lihat lib/mr-fulfillment.ts).';
