-- Create ENUMs for type safety
CREATE TYPE user_role AS ENUM ('admin', 'warehouse', 'approver', 'purchasing');

-- CABANG / LOKASI (Maps to location/branch management)
CREATE TABLE public.cabang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_cabang TEXT UNIQUE NOT NULL,
    kode_cabang TEXT UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PROFILES (Maps to users table)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    nama TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role user_role NOT NULL DEFAULT 'warehouse',
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    cabang_id BIGINT REFERENCES public.cabang(id),
    signature TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- BARANG (Maps to tb_barang)
CREATE TABLE public.barang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT UNIQUE NOT NULL,
    part_name TEXT NOT NULL,
    part_satuan TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- VENDORS (Maps to vendors)
CREATE TABLE public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_no TEXT UNIQUE NOT NULL,
    vendor_name TEXT NOT NULL,
    telephone TEXT,
    contact_name TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- CUSTOMERS (Maps to customers)
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_no TEXT UNIQUE NOT NULL,
    customer_name TEXT UNIQUE NOT NULL,
    telephone TEXT,
    contact_name TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Helper trigger for automatic updated_at tracking
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_cabang_modtime BEFORE UPDATE ON public.cabang FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_barang_modtime BEFORE UPDATE ON public.barang FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_vendors_modtime BEFORE UPDATE ON public.vendors FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_customers_modtime BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
