-- Migration: Stock Summary View and Movement Tracking
-- Enables grouped inventory monitoring and full audit trails for stock changes.

-- 1. Create Stock Movements table
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT REFERENCES public.barang(id) ON DELETE CASCADE NOT NULL,
    cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    qty_change INTEGER NOT NULL,
    type TEXT NOT NULL, -- 'PR', 'SS', 'MANUAL', 'ADJUSTMENT'
    reference_id TEXT, -- e.g., MR Code or PR Code
    notes TEXT,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create index for performance
CREATE INDEX IF NOT EXISTS idx_stock_movements_part ON public.stock_movements(part_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_cabang ON public.stock_movements(cabang_id);

-- 3. Create v_stock_summary view (Grouped by Part)
CREATE OR REPLACE VIEW public.v_stock_summary AS
SELECT 
  b.id AS part_id,
  b.part_number,
  b.part_name,
  b.part_satuan,
  COALESCE(SUM(s.qty), 0) AS total_qty,
  COUNT(s.cabang_id) FILTER (WHERE s.qty > 0) AS active_locations,
  MAX(s.updated_at) AS last_updated
FROM public.barang b
LEFT JOIN public.stock s ON b.id = s.part_id
GROUP BY b.id, b.part_number, b.part_name, b.part_satuan;
