-- Migration: Work Order Formula (BOM) + role akses wo_formula_editor
-- Date: 2026-09-20
-- Description:
--   Formula = komposisi bahan/komponen (part) yang dibutuhkan untuk
--   "memproduksi" 1 unit suatu PN target lewat Working Order. Satu PN target
--   punya maksimal satu formula (wo_formulas, UNIQUE target_part_id), berisi
--   banyak baris komponen (wo_formula_components). qty_per_unit boleh desimal
--   (mis. 0.5) -- pembulatan ke atas (CEIL) dilakukan di service layer saat
--   formula diterapkan ke stok integer, bukan di schema.
--
--   Halaman "Manajemen WO Formula" hanya boleh diakses moderator + user yang
--   dipilih manual oleh moderator. Alih-alih tabel allowlist baru, dipakai
--   ulang mekanisme user_roles yang sudah ada (user boleh punya banyak role) --
--   role 'wo_formula_editor' di sini, diberikan/dicabut lewat panel "Kelola
--   Akses" di dalam halaman WO Formula sendiri (services/wo-formula-actions.ts).

-- 1. Formula header (1 baris = 1 target PN)
CREATE TABLE IF NOT EXISTS public.wo_formulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (target_part_id)
);

-- 2. Formula components (baris-baris komposisi per formula)
CREATE TABLE IF NOT EXISTS public.wo_formula_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formula_id BIGINT REFERENCES public.wo_formulas(id) ON DELETE CASCADE NOT NULL,
    component_part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    component_part_number TEXT NOT NULL,
    component_part_name TEXT NOT NULL,
    component_satuan TEXT NOT NULL,
    qty_per_unit NUMERIC NOT NULL CHECK (qty_per_unit > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (formula_id, component_part_id)
);

-- 3. RLS (tabel baru perlu policy eksplisit, mengikuti pola consignment_ik --
--    otorisasi sebenarnya ditegakkan di service layer, bukan RLS)
ALTER TABLE public.wo_formulas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wo_formula_components ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to wo_formulas" ON public.wo_formulas;
CREATE POLICY "Allow authenticated full access to wo_formulas"
  ON public.wo_formulas FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to wo_formula_components" ON public.wo_formula_components;
CREATE POLICY "Allow authenticated full access to wo_formula_components"
  ON public.wo_formula_components FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- GRANT eksplisit -- tabel baru tidak otomatis dapat privilege (lihat
-- 20260728120000_fix_missing_table_grants.sql untuk kasus serupa).
GRANT ALL ON TABLE public.wo_formulas, public.wo_formula_components
  TO anon, authenticated, authenticator;

-- 4. Index
CREATE INDEX IF NOT EXISTS idx_wo_formulas_target_part_id ON public.wo_formulas(target_part_id);
CREATE INDEX IF NOT EXISTS idx_wo_formula_components_formula_id ON public.wo_formula_components(formula_id);

-- 5. Trigger updated_at
DROP TRIGGER IF EXISTS update_wo_formulas_modtime ON public.wo_formulas;
CREATE TRIGGER update_wo_formulas_modtime BEFORE UPDATE ON public.wo_formulas
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_wo_formula_components_modtime ON public.wo_formula_components;
CREATE TRIGGER update_wo_formula_components_modtime BEFORE UPDATE ON public.wo_formula_components
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 6. Role akses halaman WO Formula (moderator selalu boleh akses; role ini
--    dipakai untuk user tambahan yang dipilih moderator). Idempotent.
INSERT INTO public.roles (name, label, description, color)
VALUES (
  'wo_formula_editor',
  'WO Formula Editor',
  'Akses kelola Working Order Formula (dipilih manual oleh moderator)',
  'indigo'
)
ON CONFLICT (name) DO NOTHING;
