-- Migration: Update Sites and Create Approval Templates
-- Date: 2026-04-10

-- 1. Update Sites (Cabang)
-- We truncate to ensure only the specified sites are in the system.
-- Using CASCADE to handle profiles but be aware this will set cabang_id to null in profiles.
TRUNCATE public.cabang CASCADE;

INSERT INTO public.cabang (nama_cabang, kode_cabang) VALUES
  ('GMI-JAKARTA', 'JKT'),
  ('GMI-JAKARTA DS', 'JKT-DS'),
  ('GMI-MAN JAKARTA', 'MAN-JKT'),
  ('GMI-MAN BPP', 'MAN-BPP'),
  ('GMI-SERVICE JAKARTA', 'SRV-JKT'),
  ('GMI-SERVICE BPP', 'SRV-BPP'),
  ('GMI-SERVICE TABANG', 'SRV-TBG'),
  ('GMI-SERVICE ENIM', 'SRV-ENIM'),
  ('GMI-ENIM', 'ENIM'),
  ('GMI-BA', 'BA'),
  ('GMI-DIZA', 'DIZA'),
  ('GMI-MIP', 'MIP'),
  ('GMI-TAL', 'TAL'),
  ('GMI-MIFA', 'MIFA'),
  ('GMI-BPP', 'BPP'),
  ('GMI-AMI', 'AMI'),
  ('GMI-BIB', 'BIB'),
  ('GMI-IPT', 'IPT'),
  ('GMI-LKP', 'LKP');

-- 2. Create Approval Templates Table
CREATE TABLE public.approval_templates (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type        TEXT NOT NULL,
  cabang_id   BIGINT NOT NULL REFERENCES public.cabang(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT  valid_type CHECK (type IN ('Material Request', 'Purchase Request', 'Purchase Order', 'Item Transfer')),
  UNIQUE (type, cabang_id)
);

-- 3. Create Approval Template Steps Table
CREATE TABLE public.approval_template_steps (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id     BIGINT NOT NULL REFERENCES public.approval_templates(id) ON DELETE CASCADE,
  step_order      INTEGER NOT NULL,
  approver_type   TEXT NOT NULL DEFAULT 'user', -- 'user' or 'requester'
  user_id         UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  level           TEXT NOT NULL DEFAULT 'menyetujui', -- 'menyetujui' or 'mengetahui'
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT      valid_approver_type CHECK (approver_type IN ('user', 'requester')),
  CONSTRAINT      valid_level CHECK (level IN ('menyetujui', 'mengetahui'))
);

-- 4. Enable RLS
ALTER TABLE public.approval_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_template_steps ENABLE ROW LEVEL SECURITY;

-- 5. Helper Function for Admin Check (Site Specific)
CREATE OR REPLACE FUNCTION public.is_admin_of_cabang(target_cabang_id BIGINT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles ur
    JOIN public.roles r ON ur.role_id = r.id
    JOIN public.profiles p ON ur.user_id = p.id
    WHERE ur.user_id = auth.uid() 
      AND r.name = 'admin' 
      AND p.cabang_id = target_cabang_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 6. RLS Policies for approval_templates
-- Anyone authenticated can read (needed for instantiation)
CREATE POLICY "Anyone authenticated can read approval_templates"
  ON public.approval_templates FOR SELECT USING (auth.role() = 'authenticated');

-- Moderator can do anything
CREATE POLICY "Moderators have full access to approval_templates"
  ON public.approval_templates
  FOR ALL
  USING (public.is_moderator())
  WITH CHECK (public.is_moderator());

-- Admin site-specific access
CREATE POLICY "Admins can manage their own site templates"
  ON public.approval_templates
  FOR ALL
  USING (public.is_admin_of_cabang(cabang_id))
  WITH CHECK (public.is_admin_of_cabang(cabang_id));

-- 7. RLS Policies for approval_template_steps
-- Inheritance via join check
CREATE POLICY "Anyone authenticated can read approval_template_steps"
  ON public.approval_template_steps FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Moderators have full access to approval_template_steps"
  ON public.approval_template_steps
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.approval_templates t 
      WHERE t.id = approval_template_steps.template_id 
      AND public.is_moderator()
    )
  );

CREATE POLICY "Admins can manage their own site template steps"
  ON public.approval_template_steps
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.approval_templates t 
      WHERE t.id = approval_template_steps.template_id 
      AND public.is_admin_of_cabang(t.cabang_id)
    )
  );

-- 8. Add approvals column to transaction tables
ALTER TABLE public.mrs ADD COLUMN IF NOT EXISTS approvals JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.prs ADD COLUMN IF NOT EXISTS approvals JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.pos ADD COLUMN IF NOT EXISTS approvals JSONB DEFAULT '[]'::jsonb;

-- Trigger for updated_at
CREATE TRIGGER update_approval_templates_modtime BEFORE UPDATE ON public.approval_templates FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_approval_template_steps_modtime BEFORE UPDATE ON public.approval_template_steps FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

