-- Update Web: changelog/pengumuman aplikasi untuk SEMUA user login.
--
-- Menggantikan /update-logs (changelog sederhana yang cuma bisa dilihat
-- moderator+it). Diadaptasi dari fitur "Update Web" di ga-web, dengan
-- penyesuaian ke RBAC repo ini (user_roles, bukan profiles.role):
--   - Baca, reaction, komentar: semua user login.
--   - Buat/edit/hapus post + upload media: moderator yang JUGA punya role
--     "it" (sama dengan penjaga /update-logs sebelumnya).
--
-- Isi:
--   1. Helper is_update_web_publisher()
--   2. Tabel update_web_posts (versi x.y.z = 3 kolom int + generated text)
--   3. Tabel update_web_post_reactions (1 emoji aktif per user per post)
--   4. Tabel update_web_seen (badge "update baru", per akun lintas device)
--   5. RPC create_update_web_post (penomoran versi atomic)
--   6. RPC add_update_web_post_comment (komentar teks, semua user)
--   7. Storage bucket "update-web" (thumbnail + media body)
--   8. Migrasi data update_logs -> update_web_posts
--
-- BACKWARD-COMPAT: tabel update_logs & kolom profiles.last_seen_update_log_at
-- SENGAJA tidak dihapus, supaya build production lama (/update-logs) tetap
-- jalan selama deploy frontend belum selesai. Semua langkah idempotent.

-- ============================================================
-- 1. Helper: siapa yang boleh publish
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_update_web_publisher()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN public.is_moderator() AND public.is_it();
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION public.is_update_web_publisher() TO authenticated;

-- ============================================================
-- 2. update_web_posts
-- ============================================================

CREATE TABLE IF NOT EXISTS public.update_web_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_major INT NOT NULL CHECK (version_major >= 0),
  version_minor INT NOT NULL CHECK (version_minor >= 0),
  version_patch INT NOT NULL CHECK (version_patch >= 0),
  -- Generated supaya string versi tidak mungkin beda dari 3 kolom int-nya.
  version TEXT GENERATED ALWAYS AS (
    version_major::text || '.' || version_minor::text || '.' || version_patch::text
  ) STORED,
  title TEXT NOT NULL,
  thumbnail_url TEXT,
  -- Ringkasan poin singkat (string[]) untuk card & bagian atas detail.
  highlights JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Body rich text, format Tiptap JSON doc.
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Komentar append-only: [{user_id, user_name, message, timestamp}],
  -- hanya diisi lewat RPC add_update_web_post_comment.
  comments JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (version_major, version_minor, version_patch)
);

CREATE INDEX IF NOT EXISTS idx_update_web_posts_created_at
  ON public.update_web_posts (created_at DESC);

DROP TRIGGER IF EXISTS update_update_web_posts_modtime ON public.update_web_posts;
CREATE TRIGGER update_update_web_posts_modtime
  BEFORE UPDATE ON public.update_web_posts
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

ALTER TABLE public.update_web_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "update_web_posts_select" ON public.update_web_posts;
CREATE POLICY "update_web_posts_select"
  ON public.update_web_posts FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "update_web_posts_insert_publisher" ON public.update_web_posts;
CREATE POLICY "update_web_posts_insert_publisher"
  ON public.update_web_posts FOR INSERT TO authenticated
  WITH CHECK (public.is_update_web_publisher());

DROP POLICY IF EXISTS "update_web_posts_update_publisher" ON public.update_web_posts;
CREATE POLICY "update_web_posts_update_publisher"
  ON public.update_web_posts FOR UPDATE TO authenticated
  USING (public.is_update_web_publisher())
  WITH CHECK (public.is_update_web_publisher());

DROP POLICY IF EXISTS "update_web_posts_delete_publisher" ON public.update_web_posts;
CREATE POLICY "update_web_posts_delete_publisher"
  ON public.update_web_posts FOR DELETE TO authenticated
  USING (public.is_update_web_publisher());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.update_web_posts TO authenticated;

-- ============================================================
-- 3. update_web_post_reactions
-- ============================================================
-- Daftar emoji di CHECK ini HARUS sama dengan UPDATE_WEB_REACTION_EMOJIS
-- di type/update-web.ts.

CREATE TABLE IF NOT EXISTS public.update_web_post_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.update_web_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  emoji TEXT NOT NULL CHECK (emoji IN ('👍', '❤️', '🎉', '😂', '😮', '🙏')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_update_web_post_reactions_post
  ON public.update_web_post_reactions (post_id);

ALTER TABLE public.update_web_post_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "update_web_post_reactions_select" ON public.update_web_post_reactions;
CREATE POLICY "update_web_post_reactions_select"
  ON public.update_web_post_reactions FOR SELECT TO authenticated
  USING (true);

-- user_id dikunci ke auth.uid(): user tidak bisa memberi/menghapus reaction
-- atas nama orang lain, jadi tidak perlu RPC.
DROP POLICY IF EXISTS "update_web_post_reactions_insert_own" ON public.update_web_post_reactions;
CREATE POLICY "update_web_post_reactions_insert_own"
  ON public.update_web_post_reactions FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "update_web_post_reactions_delete_own" ON public.update_web_post_reactions;
CREATE POLICY "update_web_post_reactions_delete_own"
  ON public.update_web_post_reactions FOR DELETE TO authenticated
  USING (user_id = auth.uid());

GRANT SELECT, INSERT, DELETE ON public.update_web_post_reactions TO authenticated;

-- ============================================================
-- 4. update_web_seen
-- ============================================================
-- "Sudah lihat sampai post mana" per akun (bukan localStorage) supaya badge
-- konsisten lintas perangkat. Window 7 hari dihitung di client.

CREATE TABLE IF NOT EXISTS public.update_web_seen (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  last_seen_post_id BIGINT REFERENCES public.update_web_posts(id) ON DELETE SET NULL,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.update_web_seen ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "update_web_seen_select_own" ON public.update_web_seen;
CREATE POLICY "update_web_seen_select_own"
  ON public.update_web_seen FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "update_web_seen_insert_own" ON public.update_web_seen;
CREATE POLICY "update_web_seen_insert_own"
  ON public.update_web_seen FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "update_web_seen_update_own" ON public.update_web_seen;
CREATE POLICY "update_web_seen_update_own"
  ON public.update_web_seen FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE ON public.update_web_seen TO authenticated;

-- ============================================================
-- 5. RPC create_update_web_post
-- ============================================================
-- p_version NULL -> patch +1 dari versi tertinggi (1.0.0 kalau kosong).
-- FOR UPDATE mengunci baris versi tertinggi supaya 2 publisher yang posting
-- bersamaan tidak dapat nomor yang sama. Edit/hapus tidak lewat RPC (cukup
-- RLS), bentrok versi saat edit ditangkap unique constraint.

CREATE OR REPLACE FUNCTION public.create_update_web_post(
  p_title TEXT,
  p_thumbnail_url TEXT,
  p_highlights JSONB,
  p_content JSONB,
  p_version TEXT DEFAULT NULL
)
RETURNS public.update_web_posts
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_major INT;
  v_minor INT;
  v_patch INT;
  v_row public.update_web_posts%ROWTYPE;
BEGIN
  IF NOT public.is_update_web_publisher() THEN
    RAISE EXCEPTION 'Hanya moderator dengan role IT yang boleh membuat Update Web.';
  END IF;
  IF p_title IS NULL OR trim(p_title) = '' THEN
    RAISE EXCEPTION 'Judul wajib diisi.';
  END IF;

  IF p_version IS NULL THEN
    SELECT version_major, version_minor, version_patch
      INTO v_major, v_minor, v_patch
    FROM public.update_web_posts
    ORDER BY version_major DESC, version_minor DESC, version_patch DESC
    LIMIT 1
    FOR UPDATE;

    IF v_major IS NULL THEN
      v_major := 1; v_minor := 0; v_patch := 0;
    ELSE
      v_patch := v_patch + 1;
    END IF;
  ELSE
    IF p_version !~ '^\d+\.\d+\.\d+$' THEN
      RAISE EXCEPTION 'Format versi harus x.y.z (mis. 1.4.2).';
    END IF;
    v_major := split_part(p_version, '.', 1)::INT;
    v_minor := split_part(p_version, '.', 2)::INT;
    v_patch := split_part(p_version, '.', 3)::INT;
  END IF;

  INSERT INTO public.update_web_posts (
    version_major, version_minor, version_patch,
    title, thumbnail_url, highlights, content, created_by
  ) VALUES (
    v_major, v_minor, v_patch,
    trim(p_title), p_thumbnail_url, COALESCE(p_highlights, '[]'::jsonb),
    COALESCE(p_content, '{}'::jsonb), auth.uid()
  )
  RETURNING * INTO v_row;

  RETURN v_row;
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'Versi tersebut sudah dipakai postingan lain.';
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_update_web_post(TEXT, TEXT, JSONB, JSONB, TEXT) TO authenticated;

-- ============================================================
-- 6. RPC add_update_web_post_comment
-- ============================================================
-- Policy UPDATE tabel cuma untuk publisher, jadi komentar dari semua user
-- lewat RPC SECURITY DEFINER yang hanya menyentuh kolom `comments`.

CREATE OR REPLACE FUNCTION public.add_update_web_post_comment(
  p_id BIGINT,
  p_message TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_name TEXT;
  v_message TEXT := trim(COALESCE(p_message, ''));
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Session expired.';
  END IF;
  IF v_message = '' THEN
    RAISE EXCEPTION 'Komentar tidak boleh kosong.';
  END IF;
  IF length(v_message) > 2000 THEN
    RAISE EXCEPTION 'Komentar maksimal 2000 karakter.';
  END IF;

  SELECT COALESCE(nama, email, 'Unknown User') INTO v_name
  FROM public.profiles WHERE id = auth.uid();

  UPDATE public.update_web_posts
  SET comments = COALESCE(comments, '[]'::jsonb) || jsonb_build_array(
    jsonb_build_object(
      'user_id', auth.uid(),
      'user_name', v_name,
      'message', v_message,
      'timestamp', NOW()
    )
  )
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Postingan Update Web tidak ditemukan.';
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.add_update_web_post_comment(BIGINT, TEXT) TO authenticated;

-- ============================================================
-- 7. Storage bucket "update-web"
-- ============================================================
-- Public read (dipakai langsung di <img>/<video>), tulis hanya publisher.
-- Upload langsung dari browser ke Supabase, jadi tidak kena limit body
-- 4.5MB Vercel. Batas 50MB per file (samakan dengan UPDATE_WEB_MAX_UPLOAD_BYTES
-- di type/update-web.ts; limit global FILE_SIZE_LIMIT storage VPS juga harus
-- >= ini).

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('update-web', 'update-web', true, 52428800)
ON CONFLICT (id) DO UPDATE
  SET public = true, file_size_limit = EXCLUDED.file_size_limit;

DROP POLICY IF EXISTS "update_web_storage_read" ON storage.objects;
CREATE POLICY "update_web_storage_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'update-web');

DROP POLICY IF EXISTS "update_web_storage_insert" ON storage.objects;
CREATE POLICY "update_web_storage_insert"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'update-web' AND public.is_update_web_publisher());

DROP POLICY IF EXISTS "update_web_storage_update" ON storage.objects;
CREATE POLICY "update_web_storage_update"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'update-web' AND public.is_update_web_publisher());

DROP POLICY IF EXISTS "update_web_storage_delete" ON storage.objects;
CREATE POLICY "update_web_storage_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'update-web' AND public.is_update_web_publisher());

-- ============================================================
-- 8. Migrasi update_logs -> update_web_posts
-- ============================================================
-- Versi "1.02.015" -> 1.2.15. changes[] -> highlights (deskripsi) + body
-- Tiptap berisi heading per tipe (Fitur Baru / Perbaikan / Peningkatan) dan
-- bullet list. created_at mengikuti release_date (tetap pakai created_at asli
-- kalau tanggalnya sama) supaya urutan & tanggal tidak berubah, dan post lama
-- tidak menyalakan badge "baru"
-- (window 7 hari). Idempotent: versi yang sudah ada dilewati.

INSERT INTO public.update_web_posts (
  version_major, version_minor, version_patch,
  title, highlights, content, created_by, created_at, updated_at
)
SELECT
  split_part(l.version, '.', 1)::INT,
  split_part(l.version, '.', 2)::INT,
  split_part(l.version, '.', 3)::INT,
  l.title,
  COALESCE((
    SELECT jsonb_agg(c->>'description' ORDER BY ord)
    FROM jsonb_array_elements(l.changes) WITH ORDINALITY AS e(c, ord)
    WHERE trim(COALESCE(c->>'description', '')) <> ''
  ), '[]'::jsonb),
  jsonb_build_object(
    'type', 'doc',
    'content', COALESCE((
      SELECT jsonb_agg(block ORDER BY grp_order, block_order)
      FROM (
        SELECT
          g.grp_order,
          b.block_order,
          b.block
        FROM (
          VALUES ('feature', 'Fitur Baru', 1),
                 ('improvement', 'Peningkatan', 2),
                 ('fix', 'Perbaikan', 3)
        ) AS g(type, label, grp_order)
        CROSS JOIN LATERAL (
          SELECT jsonb_agg(
            jsonb_build_object(
              'type', 'listItem',
              'content', jsonb_build_array(jsonb_build_object(
                'type', 'paragraph',
                'content', jsonb_build_array(jsonb_build_object(
                  'type', 'text', 'text', c->>'description'
                ))
              ))
            ) ORDER BY ord
          ) AS items
          FROM jsonb_array_elements(l.changes) WITH ORDINALITY AS e(c, ord)
          WHERE c->>'type' = g.type
            AND trim(COALESCE(c->>'description', '')) <> ''
        ) AS li
        CROSS JOIN LATERAL (
          VALUES
            (1, jsonb_build_object(
              'type', 'heading',
              'attrs', jsonb_build_object('level', 3),
              'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', g.label))
            )),
            (2, jsonb_build_object('type', 'bulletList', 'content', li.items))
        ) AS b(block_order, block)
        WHERE li.items IS NOT NULL
      ) AS blocks
    ), '[]'::jsonb)
  ),
  l.created_by,
  CASE
    WHEN (l.created_at AT TIME ZONE 'Asia/Jakarta')::date = l.release_date
      THEN l.created_at
    ELSE (l.release_date::timestamp + TIME '09:00') AT TIME ZONE 'Asia/Jakarta'
  END,
  l.updated_at
FROM public.update_logs l
WHERE l.version ~ '^\d+\.\d+\.\d+$'
ON CONFLICT (version_major, version_minor, version_patch) DO NOTHING;
