-- Update Logs (changelog) feature.
--
-- New page /update-logs shows a list of dated version entries (versioning
-- scheme: x.xx.xxx, e.g. "1.00.000" -- 1-digit major, 2-digit minor,
-- 3-digit patch, all zero-padded so a plain TEXT column sorts correctly).
-- Managed entirely by moderators who also hold the new "it" role (this repo
-- has no "IT" role/department concept yet -- created here for the first
-- time). The page itself is only visible to moderator+it users; everyone
-- else never sees the nav item or the data (enforced both client-side and
-- via RLS).
--
-- A small unread-indicator (red dot in the sidebar) is driven by comparing
-- the newest update_logs.created_at against profiles.last_seen_update_log_at,
-- which gets bumped to NOW() when a moderator+it user opens /update-logs.

-- 1. New role "it". Idempotent.
INSERT INTO public.roles (name, label, description, color)
VALUES (
  'it',
  'IT',
  'Tim IT -- mengelola Update Logs & hal teknis lainnya',
  'slate'
)
ON CONFLICT (name) DO NOTHING;

-- Grant the "it" role to the account requesting this feature. Doesn't touch
-- any other role that account already has (e.g. moderator) -- if that
-- account isn't a moderator yet, the /update-logs page simply won't be
-- visible to it until it is, since access requires BOTH roles.
INSERT INTO public.user_roles (user_id, role_id)
SELECT p.id, r.id
FROM public.profiles p, public.roles r
WHERE p.email = 'garudamart3@gmail.com'
  AND r.name = 'it'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- 2. Read-tracking column for the unread dot.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS last_seen_update_log_at TIMESTAMPTZ;

-- 3. update_logs table.
CREATE TABLE public.update_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL UNIQUE CHECK (version ~ '^[0-9]\.[0-9]{2}\.[0-9]{3}$'),
    title TEXT NOT NULL,
    release_date DATE NOT NULL DEFAULT CURRENT_DATE,
    -- Array of { "type": "feature" | "fix" | "improvement", "description": text }
    changes JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_update_logs_release_date ON public.update_logs (release_date DESC, id DESC);

COMMENT ON TABLE public.update_logs IS
'Changelog entries per app version (x.xx.xxx), managed by moderator+it users via /update-logs.';

CREATE TRIGGER update_update_logs_modtime
  BEFORE UPDATE ON public.update_logs
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 4. RLS: only moderator AND it (both roles) may read or write.
CREATE OR REPLACE FUNCTION public.is_it()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles ur
    JOIN public.roles r ON ur.role_id = r.id
    WHERE ur.user_id = auth.uid() AND r.name = 'it'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

ALTER TABLE public.update_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Moderator+IT can read update_logs"
  ON public.update_logs FOR SELECT
  USING (public.is_moderator() AND public.is_it());

CREATE POLICY "Moderator+IT can insert update_logs"
  ON public.update_logs FOR INSERT
  WITH CHECK (public.is_moderator() AND public.is_it());

CREATE POLICY "Moderator+IT can update update_logs"
  ON public.update_logs FOR UPDATE
  USING (public.is_moderator() AND public.is_it());

CREATE POLICY "Moderator+IT can delete update_logs"
  ON public.update_logs FOR DELETE
  USING (public.is_moderator() AND public.is_it());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.update_logs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.update_logs_id_seq TO authenticated;
