-- Migration: Working Order (WO)
-- Date: 2026-09-20
-- Description:
--   WO = proses assembly/produksi internal: PN target "diproduksi" dengan
--   mengonsumsi formula (BOM) komponen dari stok Gudang WO. Satu WO merujuk
--   ke SATU MR (1 WO : 1 MR -- WO-by-PO belum didukung).
--
--   Approval memakai sistem approval_templates generic yang sudah ada
--   (type 'Working Order', lihat 20260920090000_wo_approval_type.sql),
--   dengan snapshot beku di kolom approvals JSONB -- pola yang sama persis
--   dengan mrs/prs/pos/receives/spb (lihat services/procurement-actions.ts
--   _buildApprovalFlow).
--
--   working_order_item_components adalah snapshot BEKU formula (dari
--   wo_formula_components) pada saat WO dibuat -- ini juga sekaligus data
--   utk "Material Release" (list komponen per item target, bisa dicetak).
--   applied_qty / applied_qty_required menyimpan qty yang SUDAH diterapkan
--   ke tabel stock, dipakai sebagai baseline utk penyesuaian delta saat WO
--   di-edit di status On Process (lihat services/working-order-actions.ts).

-- 1. Header
CREATE TABLE IF NOT EXISTS public.working_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_kode TEXT UNIQUE NOT NULL,
    mr_id BIGINT REFERENCES public.mrs(id) NOT NULL,
    gudang_cabang_id BIGINT REFERENCES public.cabang(id) NOT NULL,
    departemen TEXT NOT NULL,
    wo_tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    wo_pic_id UUID REFERENCES public.profiles(id) NOT NULL,

    approval_template_id BIGINT REFERENCES public.approval_templates(id) ON DELETE SET NULL,
    approvals JSONB NOT NULL DEFAULT '[]'::jsonb,
    wo_status TEXT NOT NULL DEFAULT 'Pending Approval',
    rejection_reason TEXT,

    on_process_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    closed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT wo_departemen_check CHECK (departemen IN ('HO', 'BPP')),
    CONSTRAINT wo_status_check CHECK (wo_status IN ('Pending Approval', 'On Process', 'Closed', 'Rejected'))
);

-- 2. Item lines (target PN yang di-WO-kan, merujuk ke item MR asal)
CREATE TABLE IF NOT EXISTS public.working_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_id BIGINT REFERENCES public.working_orders(id) ON DELETE CASCADE NOT NULL,
    mr_item_id BIGINT REFERENCES public.mr_items(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty INTEGER NOT NULL CHECK (qty > 0),
    lead_time_days INTEGER,
    deadline_date DATE,
    applied_qty INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Formula snapshot per item WO (= data Material Release)
CREATE TABLE IF NOT EXISTS public.working_order_item_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_item_id BIGINT REFERENCES public.working_order_items(id) ON DELETE CASCADE NOT NULL,
    component_part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    component_part_number TEXT NOT NULL,
    component_part_name TEXT NOT NULL,
    component_satuan TEXT NOT NULL,
    qty_per_unit NUMERIC NOT NULL,
    qty_required NUMERIC NOT NULL,
    applied_qty_required NUMERIC NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. RLS (pola sama seperti consignment_ik / wo_formula -- otorisasi
--    sebenarnya ditegakkan di service layer)
ALTER TABLE public.working_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.working_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.working_order_item_components ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to working_orders" ON public.working_orders;
CREATE POLICY "Allow authenticated full access to working_orders"
  ON public.working_orders FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to working_order_items" ON public.working_order_items;
CREATE POLICY "Allow authenticated full access to working_order_items"
  ON public.working_order_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to working_order_item_components" ON public.working_order_item_components;
CREATE POLICY "Allow authenticated full access to working_order_item_components"
  ON public.working_order_item_components FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.working_orders, public.working_order_items, public.working_order_item_components
  TO anon, authenticated, authenticator;

-- 5. Index
CREATE INDEX IF NOT EXISTS idx_working_orders_mr_id ON public.working_orders(mr_id);
CREATE INDEX IF NOT EXISTS idx_working_orders_gudang_cabang_id ON public.working_orders(gudang_cabang_id);
CREATE INDEX IF NOT EXISTS idx_working_orders_wo_status ON public.working_orders(wo_status);
CREATE INDEX IF NOT EXISTS idx_working_order_items_wo_id ON public.working_order_items(wo_id);
CREATE INDEX IF NOT EXISTS idx_working_order_items_mr_item_id ON public.working_order_items(mr_item_id);
CREATE INDEX IF NOT EXISTS idx_working_order_item_components_wo_item_id ON public.working_order_item_components(wo_item_id);

-- 6. Trigger updated_at
DROP TRIGGER IF EXISTS update_working_orders_modtime ON public.working_orders;
CREATE TRIGGER update_working_orders_modtime BEFORE UPDATE ON public.working_orders
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_working_order_items_modtime ON public.working_order_items;
CREATE TRIGGER update_working_order_items_modtime BEFORE UPDATE ON public.working_order_items
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_working_order_item_components_modtime ON public.working_order_item_components;
CREATE TRIGGER update_working_order_item_components_modtime BEFORE UPDATE ON public.working_order_item_components
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
