-- Migration: Penerimaan Konsinyasi (customer goods receipt) + Stok Customer
-- Date: 2026-09-15
-- Description:
--   Langkah lanjutan setelah IK (Item/Invoice Konsinyasi): staff internal
--   mencatat konfirmasi penerimaan customer atas satu IK (customer BELUM
--   punya login sendiri di sistem ini — staff yang input atas nama
--   customer, misal setelah konfirmasi telepon/WA/TTD fisik saat serah
--   terima). Per item IK: qty_terima + status ('sesuai'/'komplain').
--
--   Qty yang diterima (qty_terima) SELALU dianggap sudah berpindah secara
--   fisik ke customer, terlepas dari status-nya — karena itu barang yang
--   benar-benar diterima/dikuasai customer saat serah terima. qty_terima
--   dipindahkan dari stok gudang tujuan (ke_cabang_id milik IK) ke
--   customer_stock (stok konsinyasi yang ada di customer). Selisih
--   (qty_kirim - qty_terima) TETAP di stok gudang tujuan — belum diterima
--   customer, jadi masih tanggung jawab GMI, pending tindak lanjut manual
--   (redelivery via IK baru, dsb).
--
--   status = 'komplain' cuma penanda ada masalah (qty kurang dan/atau
--   kualitas) buat tindak lanjut manual (resolution_status open/selesai +
--   catatan) — TIDAK otomatis menahan/membatalkan qty_terima yang sudah
--   dikuasai customer.
--
--   Satu IK hanya boleh punya SATU dokumen penerimaan (UNIQUE ik_id) —
--   kalau customer terima sisa kiriman/redelivery, itu dikirim lewat IK
--   baru lalu penerimaan baru lagi.

-- 1. Stok Konsinyasi di Customer (analog `stock` tapi keyed ke customer,
--    bukan cabang).
CREATE TABLE IF NOT EXISTS public.customer_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    qty INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT customer_stock_unique UNIQUE (customer_id, part_id)
);

-- 2. Header
CREATE TABLE IF NOT EXISTS public.consignment_penerimaan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    penerimaan_kode TEXT UNIQUE NOT NULL,
    tanggal_terima DATE NOT NULL DEFAULT CURRENT_DATE,
    ik_id BIGINT REFERENCES public.consignment_ik(id) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) NOT NULL,
    nama_penerima TEXT NOT NULL,
    catatan TEXT,

    created_by UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT consignment_penerimaan_ik_unique UNIQUE (ik_id)
);

-- 3. Item lines (1 baris = 1 item IK yang dikonfirmasi)
CREATE TABLE IF NOT EXISTS public.consignment_penerimaan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    penerimaan_id BIGINT REFERENCES public.consignment_penerimaan(id) ON DELETE CASCADE NOT NULL,
    ik_item_id BIGINT REFERENCES public.consignment_ik_items(id) NOT NULL,
    part_id BIGINT REFERENCES public.barang(id) NOT NULL,
    part_number TEXT NOT NULL,
    part_name TEXT NOT NULL,
    satuan TEXT NOT NULL,
    qty_kirim INTEGER NOT NULL CHECK (qty_kirim > 0),
    qty_terima INTEGER NOT NULL CHECK (qty_terima >= 0 AND qty_terima <= qty_kirim),
    status TEXT NOT NULL CHECK (status IN ('sesuai', 'komplain')),
    catatan_komplain TEXT,
    resolution_status TEXT CHECK (resolution_status IN ('open', 'selesai')),
    catatan_resolusi TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. RLS
ALTER TABLE public.customer_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consignment_penerimaan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consignment_penerimaan_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to customer_stock" ON public.customer_stock;
CREATE POLICY "Allow authenticated full access to customer_stock"
  ON public.customer_stock FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to consignment_penerimaan" ON public.consignment_penerimaan;
CREATE POLICY "Allow authenticated full access to consignment_penerimaan"
  ON public.consignment_penerimaan FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to consignment_penerimaan_items" ON public.consignment_penerimaan_items;
CREATE POLICY "Allow authenticated full access to consignment_penerimaan_items"
  ON public.consignment_penerimaan_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- GRANT eksplisit: tabel baru tidak otomatis dapat privilege dari
-- 20260407230007_grant_schema_usage_to_anon.sql (GRANT tidak retroaktif).
GRANT ALL ON TABLE public.customer_stock, public.consignment_penerimaan, public.consignment_penerimaan_items
  TO anon, authenticated, authenticator;

-- 5. Index
CREATE INDEX IF NOT EXISTS idx_customer_stock_customer ON public.customer_stock(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_stock_part ON public.customer_stock(part_id);
CREATE INDEX IF NOT EXISTS idx_consignment_penerimaan_ik ON public.consignment_penerimaan(ik_id);
CREATE INDEX IF NOT EXISTS idx_consignment_penerimaan_customer ON public.consignment_penerimaan(customer_id);
CREATE INDEX IF NOT EXISTS idx_consignment_penerimaan_items_penerimaan ON public.consignment_penerimaan_items(penerimaan_id);
CREATE INDEX IF NOT EXISTS idx_consignment_penerimaan_items_ik_item ON public.consignment_penerimaan_items(ik_item_id);
CREATE INDEX IF NOT EXISTS idx_consignment_penerimaan_items_status ON public.consignment_penerimaan_items(status);

-- 6. Trigger updated_at (mengikuti pola tabel lain)
DROP TRIGGER IF EXISTS update_customer_stock_modtime ON public.customer_stock;
CREATE TRIGGER update_customer_stock_modtime BEFORE UPDATE ON public.customer_stock
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_consignment_penerimaan_modtime ON public.consignment_penerimaan;
CREATE TRIGGER update_consignment_penerimaan_modtime BEFORE UPDATE ON public.consignment_penerimaan
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_consignment_penerimaan_items_modtime ON public.consignment_penerimaan_items;
CREATE TRIGGER update_consignment_penerimaan_items_modtime BEFORE UPDATE ON public.consignment_penerimaan_items
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 7. Report view: stok konsinyasi per customer (dipakai halaman "Stok di
--    Customer").
CREATE OR REPLACE VIEW public.v_customer_stock AS
SELECT
    cs.id,
    cs.customer_id,
    c.customer_no,
    c.customer_name,
    cs.part_id,
    b.part_number,
    b.part_name,
    b.part_satuan,
    cs.qty,
    cs.updated_at
FROM public.customer_stock cs
JOIN public.customers c ON c.id = cs.customer_id
JOIN public.barang b ON b.id = cs.part_id
WHERE cs.qty <> 0;
